package com.algaworks.algalog.api.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.http.HttpServletResponse;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.algaworks.algalog.domain.model.Cliente;
import com.algaworks.algalog.domain.repository.ClienteRepository;

import lombok.AllArgsConstructor;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

@AllArgsConstructor
@RestController
public class ClienteController {

	private ClienteRepository clienteRepository;

	@GetMapping("/clientes")
	public List<Cliente> listar(HttpServletResponse response) {
		System.out.println(response.getHeaderNames());
		return clienteRepository.findByNomeContaining("i");
	}

	@GetMapping("/verify")
	public void verify(HttpServletResponse response) throws IOException {
		response.setHeader("access-token", "wRaWuwrEV4FotethASPlxusp23i3iChotH8mLs5E");
		response.addHeader("Set-Cookie", "access-token=wRaWuwrEV4FotethASPlxusp23i3iChotH8mLs5E");
		response.addHeader("Set-Header", "access-token=wRaWuwrEV4FotethASPlxusp23i3iChotH8mLs5E");
		System.out.println("isso ~´e um teste: " + response.getHeaderNames());
		response.sendRedirect(
				"https://azimute--tst1.custhelp.com/cc/submit/open/30926?access-token=wRaWuwrEV4FotethASPlxusp23i3iChotH8mLs5E");
	}

	@RequestMapping("/open/{id}")
	public String getHtmlResponse(@PathVariable String id) throws Exception {
		OkHttpClient httpClient = new OkHttpClient();
		Request request = new Request.Builder().url("https://azimute--tst1.custhelp.com/cc/submit/open/" + id)
				.addHeader("Accept", "text/html")
				.addHeader("access-token", "wRaWuwrEV4FotethASPlxusp23i3iChotH8mLs5E")
				.addHeader("access_token", "wRaWuwrEV4FotethASPlxusp23i3iChotH8mLs5E")
				//.addHeader("Accept-Encoding", "gzip, deflate, br")
				.addHeader("Connection", "keep-alive")
				.get().build();
		System.out.println(request.headers());
		Response response = httpClient.newCall(request).execute();
		//System.out.println(response.headers());
		return "<!DOCTYPE html>\r\n"
				+ "<html lang=\"en-US\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "	<meta charset=\"utf-8\" />\r\n"
				+ "	<title>[BR2022321] Ambos - Chamada Ativa</title>\r\n"
				+ "	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n"
				+ "	<!--[if lt IE 9]><script src=\"/euf/core/static/html5.js\"></script><![endif]-->\r\n"
				+ "\r\n"
				+ "	<style type='text/css'>\r\n"
				+ "		<!-- \r\n"
				+ "		.rn_ScreenReaderOnly {\r\n"
				+ "			position: absolute;\r\n"
				+ "			height: 1px;\r\n"
				+ "			left: -10000px;\r\n"
				+ "			overflow: hidden;\r\n"
				+ "			top: auto;\r\n"
				+ "			width: 1px;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		.rn_Hidden {\r\n"
				+ "			display: none !important;\r\n"
				+ "		}\r\n"
				+ "		-->\r\n"
				+ "	</style>\r\n"
				+ "	<base href='https://azimute--tst1.custhelp.com/euf/generated/optimized/1654817501/themes/pfizer/' />\r\n"
				+ "	<link href='/euf/generated/optimized/1654817501/templates/pfizer.themes.pfizer.SITE.css' rel='stylesheet'\r\n"
				+ "		type='text/css' media='all' />\r\n"
				+ "	<style type=\"text/css\">\r\n"
				+ "		<!--\r\n"
				+ "		.rn_FormSubmit img {\r\n"
				+ "			vertical-align: middle;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		.rn_IncidentThreadDisplay .rn_ThreadContent {\r\n"
				+ "			word-wrap: break-word;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		.rn_IncidentThreadDisplay p.MsoNormal,\r\n"
				+ "		.rn_IncidentThreadDisplay li.MsoNormal,\r\n"
				+ "		.rn_IncidentThreadDisplay div.MsoNormal {\r\n"
				+ "			margin: 0;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		.rn_IncidentThreadDisplay p.MsoListParagraph,\r\n"
				+ "		.rn_IncidentThreadDisplay li.MsoListParagraph,\r\n"
				+ "		.rn_IncidentThreadDisplay div.MsoListParagraph {\r\n"
				+ "			margin: 0 0 0 48px;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		.rn_SelectionInput.rn_SelectionInput {}\r\n"
				+ "\r\n"
				+ "		.rn_DateInput.rn_DateInput {}\r\n"
				+ "\r\n"
				+ "		.ets_form .rn_DateInput legend.ets_label label {\r\n"
				+ "			font-weight: bold;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		.ets_form .rn_DateInput legend.ets_label {\r\n"
				+ "			margin-left: 0;\r\n"
				+ "			padding: 0;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		.rn_TextInput .rn_HintBox {\r\n"
				+ "			border: 1px solid #DBDBDB;\r\n"
				+ "			max-width: 200px;\r\n"
				+ "			padding: 4px 16px 2px;\r\n"
				+ "			word-wrap: break-word;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		.rn_TextInput .rn_HintBox.rn_AlwaysVisibleHint {\r\n"
				+ "			max-width: 300px;\r\n"
				+ "			opacity: 1;\r\n"
				+ "			z-index: 0;\r\n"
				+ "		}\r\n"
				+ "		-->\r\n"
				+ "	</style>\r\n"
				+ "\r\n"
				+ "	<link rel=\"icon\" href=\"/euf/assets/images/favicon.png\" type=\"image/png\" />\r\n"
				+ "	<script type=\"text/javascript\">\r\n"
				+ "		<!--\r\n"
				+ "		if (parent !== self) {\r\n"
				+ "        top.location.href = location.href;\r\n"
				+ "    }\r\n"
				+ "    else if (top !== self) {\r\n"
				+ "        top.location.href = self.document.location;\r\n"
				+ "    }\r\n"
				+ "    //\r\n"
				+ "		-->\r\n"
				+ "	</script>\r\n"
				+ "\r\n"
				+ "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
				+ "	<script type=\"text/javascript\" async=\"\" src=\"//img04.en25.com/i/elqCfg.min.js\"></script>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body class=\"yui-skin-sam yui3-skin-sam\" itemscope itemtype=\"http://schema.org/WebPage\">\r\n"
				+ "	<a href=\"#rn_MainContent\" class=\"rn_SkipNav rn_ScreenReaderOnly\">Skip Navigation</a>\r\n"
				+ "	<header>\r\n"
				+ "		<div id=\"tmlc_Logo\">\r\n"
				+ "			<a\r\n"
				+ "				href=\"https://www.pfizer.com.br/\"><img src=\"/euf/assets/themes/pfizer/images/Pfizer_logo.png\" alt=\"Pfizer\" style=\"float:left;padding:17px\"></img></a>\r\n"
				+ "		</div>\r\n"
				+ "	</header>\r\n"
				+ "	<div class=\"rn_Body\">\r\n"
				+ "		<div class=\"rn_MainColumn\" role=\"main\">\r\n"
				+ "			_\r\n"
				+ "			<div class=\"rn_IncidentDetail rn_Container\">\r\n"
				+ "				<div class=\"rn_PageContent rn_KBAnswerList\">\r\n"
				+ "					<h1>\r\n"
				+ "						<center>ID CEP: 037725 PROGRAMA MUITO BEM VINDO BR2022321</center>\r\n"
				+ "					</h1>\r\n"
				+ "					<h3>\r\n"
				+ "						<center>\r\n"
				+ "							<p>FORMULÁRIO DE INFORMAÇÃO DE SEGURANÇA</p>\r\n"
				+ "						</center>\r\n"
				+ "					</h3>\r\n"
				+ "					<form id=\"rn_UpdateQuestion\" method=\"post\" action=\"/ci/ajaxRequest/sendForm\">\r\n"
				+ "						<div id=\"rn_ErrorLocation\"></div>\r\n"
				+ "						<div class=\"rn_Hidden\">\r\n"
				+ "							<!-- <rn:widget path=\"input/ProductCategoryInput\" name=\"Incident.Product\" required_lvl=\"1\" label_input=\"Topic\" label_nothing_selected=\"Select a Topic\" default_value=\"1425\"/>\r\n"
				+ "				<rn:widget path=\"input/ProductCategoryInput\" name=\"Incident.Category\" required_lvl=\"1\" label_input=\"Category\" label_nothing_selected=\"Select a Category\" default_value=\"1421\"/> -->\r\n"
				+ "						</div>\r\n"
				+ "						<div class=\"cst_BlueBox\">\r\n"
				+ "							<div class=\"cst_Left\">\r\n"
				+ "								<div id=\"rn_FieldDisplay_4\" class=\"rn_FieldDisplay rn_Output\">\r\n"
				+ "									<span class=\"rn_DataLabel\"><b>Instrutor(a)/Educador(a)/Visitador(a):</b> </span>\r\n"
				+ "									<div class=\"rn_DataValue\">\r\n"
				+ "										Thaina Pfizer </div>\r\n"
				+ "								</div>\r\n"
				+ "							</div>\r\n"
				+ "							<div class=\"cst_Right\">\r\n"
				+ "								&nbsp;\r\n"
				+ "							</div>\r\n"
				+ "							<div class=\"cst_Left\">\r\n"
				+ "								<div id=\"rn_FieldDisplay_6\" class=\"rn_FieldDisplay rn_Output\">\r\n"
				+ "									<span class=\"rn_DataLabel\"><b>Relato de Farmacovigilância:</b>  </span>\r\n"
				+ "									<div class=\"rn_DataValue\">\r\n"
				+ "										Sim </div>\r\n"
				+ "								</div>\r\n"
				+ "							</div>\r\n"
				+ "							<div class=\"cst_Right\">\r\n"
				+ "								<div id=\"rn_FieldDisplay_8\" class=\"rn_FieldDisplay rn_Output\">\r\n"
				+ "									<span class=\"rn_DataLabel\"><b>Relato de Queixa Técnica:</b>  </span>\r\n"
				+ "									<div class=\"rn_DataValue\">\r\n"
				+ "										Sim </div>\r\n"
				+ "								</div>\r\n"
				+ "							</div>\r\n"
				+ "							<div class=\"cst_Left\">\r\n"
				+ "								<div id=\"rn_FieldDisplay_10\" class=\"rn_FieldDisplay rn_Output\">\r\n"
				+ "									<span class=\"rn_DataLabel\"><b>Colhido em:</b> </span>\r\n"
				+ "									<div class=\"rn_DataValue\">\r\n"
				+ "										Chamada Ativa </div>\r\n"
				+ "								</div>\r\n"
				+ "							</div>\r\n"
				+ "						</div>\r\n"
				+ "						<div class=\"cst_WhiteBox\">\r\n"
				+ "							<div id=\"rn_TextInput_12\" class=\"rn_TextInput rn_Input\">\r\n"
				+ "								<div id=\"rn_TextInput_12_LabelContainer\">\r\n"
				+ "									<label for=\"rn_TextInput_12_Incident.CustomFields.AzimutePTC.Narrativa\" id=\"rn_TextInput_12_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Descrição do Relato:</b>                                </label>\r\n"
				+ "								</div>\r\n"
				+ "								<textarea id=\"rn_TextInput_12_Incident.CustomFields.AzimutePTC.Narrativa\" class=\"rn_TextArea\" rows=\"7\" cols=\"60\" name=\"Incident.CustomFields.AzimutePTC.Narrativa\" maxlength='1048576'></textarea>\r\n"
				+ "							</div>\r\n"
				+ "							<div id=\"rn_TextInput_14\" class=\"rn_TextInput rn_Input\">\r\n"
				+ "								<div id=\"rn_TextInput_14_LabelContainer\">\r\n"
				+ "									<label for=\"rn_TextInput_14_Incident.CustomFields.Azimute.DtEstimadaParto\" id=\"rn_TextInput_14_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Em caso de uso na gestação, data prevista para o parto:</b>                                </label>\r\n"
				+ "								</div>\r\n"
				+ "								<input type=\"text\" id=\"rn_TextInput_14_Incident.CustomFields.Azimute.DtEstimadaParto\" name=\"Incident.CustomFields.Azimute.DtEstimadaParto\" class=\"rn_Text\" maxlength='10'  />\r\n"
				+ "    </div>\r\n"
				+ "								<div id=\"rn_TextInput_16\" class=\"rn_TextInput rn_Input\">\r\n"
				+ "									<div id=\"rn_TextInput_16_LabelContainer\">\r\n"
				+ "										<label for=\"rn_TextInput_16_Incident.CustomFields.c.dt_day0\" id=\"rn_TextInput_16_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Data de conhecimento da informação: </b>                                </label>\r\n"
				+ "									</div>\r\n"
				+ "									<input type=\"text\" id=\"rn_TextInput_16_Incident.CustomFields.c.dt_day0\" name=\"Incident.CustomFields.c.dt_day0\" class=\"rn_Text\" maxlength='18'  />\r\n"
				+ "    </div>\r\n"
				+ "								</div>\r\n"
				+ "								<div class=\"cst_BlueBox\" style=\"display: inline;\">\r\n"
				+ "									<h3>\r\n"
				+ "										<center>Dados do Paciente</center>\r\n"
				+ "									</h3>\r\n"
				+ "									<div class=\"cst_Left\">\r\n"
				+ "										<div id=\"rn_FieldDisplay_18\" class=\"rn_FieldDisplay rn_Output\">\r\n"
				+ "											<span class=\"rn_DataLabel\"><b>Nome: </b> </span>\r\n"
				+ "											<div class=\"rn_DataValue\">\r\n"
				+ "												Vinicius Santos NI </div>\r\n"
				+ "										</div>\r\n"
				+ "									</div>\r\n"
				+ "									<div class=\"cst_Right\">\r\n"
				+ "										<div id=\"rn_FieldDisplay_20\" class=\"rn_FieldDisplay rn_Output\">\r\n"
				+ "											<span class=\"rn_DataLabel\"><b>Sexo: </b> </span>\r\n"
				+ "											<div class=\"rn_DataValue\">\r\n"
				+ "												Masculino </div>\r\n"
				+ "										</div>\r\n"
				+ "									</div>\r\n"
				+ "									<div id=\"rn_TextInput_22\" class=\"rn_TextInput rn_Input\">\r\n"
				+ "										<div id=\"rn_TextInput_22_LabelContainer\">\r\n"
				+ "											<label for=\"rn_TextInput_22_Incident.CustomFields.c.pat_dob\" id=\"rn_TextInput_22_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Idade: </b>                                </label>\r\n"
				+ "										</div>\r\n"
				+ "										<input type=\"text\" id=\"rn_TextInput_22_Incident.CustomFields.c.pat_dob\" name=\"Incident.CustomFields.c.pat_dob\" class=\"rn_Text\" maxlength='20' value='1990-2-18' />\r\n"
				+ "    </div>\r\n"
				+ "									</div>\r\n"
				+ "									<div class=\"cst_WhiteBox\"></div>\r\n"
				+ "									<div class=\"cst_BlueBox\">\r\n"
				+ "										<h3>\r\n"
				+ "											<center>Produto Suspeito e Apresentação</center>\r\n"
				+ "										</h3>\r\n"
				+ "										<div id=\"rn_FieldDisplay_24\" class=\"rn_FieldDisplay rn_Output\">\r\n"
				+ "											<span class=\"rn_DataLabel\"><b>Produto:</b>  </span>\r\n"
				+ "											<div class=\"rn_DataValue\">\r\n"
				+ "												FABRAZYME </div>\r\n"
				+ "										</div>\r\n"
				+ "										<div id=\"rn_TextInput_26\" class=\"rn_TextInput rn_Input\">\r\n"
				+ "											<div id=\"rn_TextInput_26_LabelContainer\">\r\n"
				+ "												<label for=\"rn_TextInput_26_Incident.CustomFields.c.product_name\" id=\"rn_TextInput_26_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Outro Produto (Se houver): </b>                                </label>\r\n"
				+ "											</div>\r\n"
				+ "											<input type=\"text\" id=\"rn_TextInput_26_Incident.CustomFields.c.product_name\" name=\"Incident.CustomFields.c.product_name\" class=\"rn_Text\" maxlength='60'  />\r\n"
				+ "    </div>\r\n"
				+ "											<div id=\"rn_TextInput_28\" class=\"rn_TextInput rn_Input\">\r\n"
				+ "												<div id=\"rn_TextInput_28_LabelContainer\">\r\n"
				+ "													<label for=\"rn_TextInput_28_Incident.CustomFields.c.prod_route_administration\" id=\"rn_TextInput_28_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Especificar apresentação: </b>                                </label>\r\n"
				+ "												</div>\r\n"
				+ "												<input type=\"text\" id=\"rn_TextInput_28_Incident.CustomFields.c.prod_route_administration\" name=\"Incident.CustomFields.c.prod_route_administration\" class=\"rn_Text\" maxlength='40'  />\r\n"
				+ "    </div>\r\n"
				+ "												<div id=\"rn_TextInput_30\" class=\"rn_TextInput rn_Input\">\r\n"
				+ "													<div id=\"rn_TextInput_30_LabelContainer\">\r\n"
				+ "														<label for=\"rn_TextInput_30_Incident.CustomFields.c.prod_dt_onset\" id=\"rn_TextInput_30_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Data de Início do Tratamento: </b>                                    <span class=\"rn_ScreenReaderOnly\">Therapy Start Date</span>\r\n"
				+ "                </label>\r\n"
				+ "													</div>\r\n"
				+ "													<input type=\"text\" id=\"rn_TextInput_30_Incident.CustomFields.c.prod_dt_onset\" name=\"Incident.CustomFields.c.prod_dt_onset\" class=\"rn_Text\" maxlength='18'  />\r\n"
				+ "    </div>\r\n"
				+ "													<div id=\"rn_SelectionInput_32\"\r\n"
				+ "														class=\"rn_SelectionInput rn_SelectionInput rn_Input\">\r\n"
				+ "														<div id=\"rn_SelectionInput_32_LabelContainer\">\r\n"
				+ "															<label for=\"rn_SelectionInput_32_Incident.CustomFields.c.prod_therapy_interrupted\" id=\"rn_SelectionInput_32_Label\" class=\"rn_Label\"><b>Paciente em tratamento: </b>                        </label>\r\n"
				+ "														</div>\r\n"
				+ "														<select id=\"rn_SelectionInput_32_Incident.CustomFields.c.prod_therapy_interrupted\" name=\"Incident.CustomFields.c.prod_therapy_interrupted\">\r\n"
				+ "            <option value=\"\">--</option>\r\n"
				+ "                            <option value=\"252\" >Sim</option>\r\n"
				+ "                    <option value=\"253\" >Não</option>\r\n"
				+ "                    <option value=\"345\" >NI</option>\r\n"
				+ "                    <option value=\"316\" >NA</option>\r\n"
				+ "                    <option value=\"364\" >Não Informado</option>\r\n"
				+ "                    <option value=\"365\" >Desconhecido</option>\r\n"
				+ "                </select>\r\n"
				+ "													</div>\r\n"
				+ "													<div id=\"rn_TextInput_34\" class=\"rn_TextInput rn_Input\">\r\n"
				+ "														<div id=\"rn_TextInput_34_LabelContainer\">\r\n"
				+ "															<label for=\"rn_TextInput_34_Incident.CustomFields.c.therapy_stop_dt\" id=\"rn_TextInput_34_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Data de Término do Tratamento: </b>                                    <span class=\"rn_ScreenReaderOnly\">Outcome Therapy Date</span>\r\n"
				+ "                </label>\r\n"
				+ "														</div>\r\n"
				+ "														<input type=\"text\" id=\"rn_TextInput_34_Incident.CustomFields.c.therapy_stop_dt\" name=\"Incident.CustomFields.c.therapy_stop_dt\" class=\"rn_Text\" maxlength='18'  />\r\n"
				+ "    </div>\r\n"
				+ "														<div id=\"rn_TextInput_36\" class=\"rn_TextInput rn_Input\">\r\n"
				+ "															<div id=\"rn_TextInput_36_LabelContainer\">\r\n"
				+ "																<label for=\"rn_TextInput_36_Incident.CustomFields.c.prod_batch_number\" id=\"rn_TextInput_36_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Lote: </b>                                </label>\r\n"
				+ "															</div>\r\n"
				+ "															<input type=\"text\" id=\"rn_TextInput_36_Incident.CustomFields.c.prod_batch_number\" name=\"Incident.CustomFields.c.prod_batch_number\" class=\"rn_Text\" maxlength='40'  />\r\n"
				+ "    </div>\r\n"
				+ "															<div id=\"rn_SelectionInput_38\"\r\n"
				+ "																class=\"rn_SelectionInput rn_SelectionInput rn_Input\">\r\n"
				+ "																<div id=\"rn_SelectionInput_38_LabelContainer\">\r\n"
				+ "																	<label for=\"rn_SelectionInput_38_Incident.CustomFields.Pfizer.MotivoNaoLote\" id=\"rn_SelectionInput_38_Label\" class=\"rn_Label\"><b>Se não houver, informar o motivo:</b>                        </label>\r\n"
				+ "																</div>\r\n"
				+ "																<select id=\"rn_SelectionInput_38_Incident.CustomFields.Pfizer.MotivoNaoLote\" name=\"Incident.CustomFields.Pfizer.MotivoNaoLote\">\r\n"
				+ "            <option value=\"\">--</option>\r\n"
				+ "                            <option value=\"1\" >Relator não possui o produto no momento</option>\r\n"
				+ "                    <option value=\"2\" >Relator não quis informar o núm do LOTE</option>\r\n"
				+ "                    <option value=\"3\" >O produto já foi descartado</option>\r\n"
				+ "                    <option value=\"4\" >LOTE não questionado</option>\r\n"
				+ "                    <option value=\"5\" >Outro</option>\r\n"
				+ "                </select>\r\n"
				+ "															</div>\r\n"
				+ "															<div id=\"rn_TextInput_40\" class=\"rn_TextInput rn_Input\">\r\n"
				+ "																<div id=\"rn_TextInput_40_LabelContainer\">\r\n"
				+ "																	<label for=\"rn_TextInput_40_Incident.CustomFields.Pfizer.OutroMotivoNaoLote\" id=\"rn_TextInput_40_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Especificar o motivo de não informação do lote:</b>                                </label>\r\n"
				+ "																</div>\r\n"
				+ "																<input type=\"text\" id=\"rn_TextInput_40_Incident.CustomFields.Pfizer.OutroMotivoNaoLote\" name=\"Incident.CustomFields.Pfizer.OutroMotivoNaoLote\" class=\"rn_Text\" maxlength='150'  />\r\n"
				+ "    </div>\r\n"
				+ "															</div>\r\n"
				+ "															<div class=\"cst_WhiteBox\"></div>\r\n"
				+ "															<div class=\"cst_BlueBox\">\r\n"
				+ "																<h3>\r\n"
				+ "																	<center>Dados do Relator</center>\r\n"
				+ "																</h3>\r\n"
				+ "																<div id=\"rn_SelectionInput_42\"\r\n"
				+ "																	class=\"rn_SelectionInput rn_SelectionInput rn_Input\">\r\n"
				+ "																	<div id=\"rn_SelectionInput_42_LabelContainer\">\r\n"
				+ "																		<label for=\"rn_SelectionInput_42_Incident.CustomFields.c.reporter_allow_contact\" id=\"rn_SelectionInput_42_Label\" class=\"rn_Label\"><b>Autoriza contato do departamento responsável, se necessário? </b>                        </label>\r\n"
				+ "																	</div>\r\n"
				+ "																	<select id=\"rn_SelectionInput_42_Incident.CustomFields.c.reporter_allow_contact\" name=\"Incident.CustomFields.c.reporter_allow_contact\">\r\n"
				+ "            <option value=\"\">--</option>\r\n"
				+ "                            <option value=\"249\" >Sim</option>\r\n"
				+ "                    <option value=\"250\" >Não</option>\r\n"
				+ "                    <option value=\"251\" >Não Questionado</option>\r\n"
				+ "                    <option value=\"356\" >Desconhecido</option>\r\n"
				+ "                    <option value=\"357\" >Não Informado</option>\r\n"
				+ "                </select>\r\n"
				+ "																</div>\r\n"
				+ "																<div id=\"rn_TextInput_44\" class=\"rn_TextInput rn_Input\">\r\n"
				+ "																	<div id=\"rn_TextInput_44_LabelContainer\">\r\n"
				+ "																		<label for=\"rn_TextInput_44_Incident.CustomFields.c.reporter_other_type\" id=\"rn_TextInput_44_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Especificar o motivo de não questionado: </b>                                </label>\r\n"
				+ "																	</div>\r\n"
				+ "																	<input type=\"text\" id=\"rn_TextInput_44_Incident.CustomFields.c.reporter_other_type\" name=\"Incident.CustomFields.c.reporter_other_type\" class=\"rn_Text\" maxlength='127'  />\r\n"
				+ "    </div>\r\n"
				+ "																	<div id=\"rn_TextInput_46\"\r\n"
				+ "																		class=\"rn_TextInput rn_Input\">\r\n"
				+ "																		<div id=\"rn_TextInput_46_LabelContainer\">\r\n"
				+ "																			<label for=\"rn_TextInput_46_Incident.CustomFields.c.rep_fullname\" id=\"rn_TextInput_46_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Nome Completo: </b>                                </label>\r\n"
				+ "																		</div>\r\n"
				+ "																		<input type=\"text\" id=\"rn_TextInput_46_Incident.CustomFields.c.rep_fullname\" name=\"Incident.CustomFields.c.rep_fullname\" class=\"rn_Text\" maxlength='150'  />\r\n"
				+ "    </div>\r\n"
				+ "																		<div id=\"rn_TextInput_48\"\r\n"
				+ "																			class=\"rn_TextInput rn_Input\">\r\n"
				+ "																			<div id=\"rn_TextInput_48_LabelContainer\">\r\n"
				+ "																				<label for=\"rn_TextInput_48_Incident.CustomFields.c.rep_occupation\" id=\"rn_TextInput_48_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Profissão:</b>                                </label>\r\n"
				+ "																			</div>\r\n"
				+ "																			<input type=\"text\" id=\"rn_TextInput_48_Incident.CustomFields.c.rep_occupation\" name=\"Incident.CustomFields.c.rep_occupation\" class=\"rn_Text\" maxlength='127'  />\r\n"
				+ "    </div>\r\n"
				+ "																			<div id=\"rn_TextInput_50\"\r\n"
				+ "																				class=\"rn_TextInput rn_Input\">\r\n"
				+ "																				<div\r\n"
				+ "																					id=\"rn_TextInput_50_LabelContainer\">\r\n"
				+ "																					<label for=\"rn_TextInput_50_Incident.CustomFields.c.rep_phone_number\" id=\"rn_TextInput_50_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Telefone: </b>                                </label>\r\n"
				+ "																				</div>\r\n"
				+ "																				<input type=\"text\" id=\"rn_TextInput_50_Incident.CustomFields.c.rep_phone_number\" name=\"Incident.CustomFields.c.rep_phone_number\" class=\"rn_Text\" maxlength='40'  />\r\n"
				+ "    </div>\r\n"
				+ "																				<div id=\"rn_TextInput_52\"\r\n"
				+ "																					class=\"rn_TextInput rn_Input\">\r\n"
				+ "																					<div\r\n"
				+ "																						id=\"rn_TextInput_52_LabelContainer\">\r\n"
				+ "																						<label for=\"rn_TextInput_52_Incident.CustomFields.c.rep_email\" id=\"rn_TextInput_52_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Email: </b>                                </label>\r\n"
				+ "																					</div>\r\n"
				+ "																					<input type=\"text\" id=\"rn_TextInput_52_Incident.CustomFields.c.rep_email\" name=\"Incident.CustomFields.c.rep_email\" class=\"rn_Text\" maxlength='80'  />\r\n"
				+ "    </div>\r\n"
				+ "																					<div id=\"rn_SelectionInput_54\"\r\n"
				+ "																						class=\"rn_SelectionInput rn_SelectionInput rn_Input\">\r\n"
				+ "																						<div\r\n"
				+ "																							id=\"rn_SelectionInput_54_LabelContainer\">\r\n"
				+ "																							<label for=\"rn_SelectionInput_54_Incident.CustomFields.c.rep_fale_pfizer\" id=\"rn_SelectionInput_54_Label\" class=\"rn_Label\"><b>Em caso de queixa técnica, foi orientado contato com o Fale Pfizer?</b>                        </label>\r\n"
				+ "																						</div>\r\n"
				+ "																						<select id=\"rn_SelectionInput_54_Incident.CustomFields.c.rep_fale_pfizer\" name=\"Incident.CustomFields.c.rep_fale_pfizer\">\r\n"
				+ "            <option value=\"\">--</option>\r\n"
				+ "                            <option value=\"241\" >Sim</option>\r\n"
				+ "                    <option value=\"346\" >Não</option>\r\n"
				+ "                    <option value=\"242\" >NI</option>\r\n"
				+ "                    <option value=\"359\" >Não relatado</option>\r\n"
				+ "                    <option value=\"360\" >Desconhecido</option>\r\n"
				+ "                </select>\r\n"
				+ "																					</div>\r\n"
				+ "																				</div>\r\n"
				+ "																				<div class=\"cst_WhiteBox\"></div>\r\n"
				+ "																				<div class=\"cst_BlueBox\">\r\n"
				+ "																					<h3>\r\n"
				+ "																						<center>Dados do Profissional de\r\n"
				+ "																							Saúde</center>\r\n"
				+ "																					</h3>\r\n"
				+ "																					<div id=\"rn_SelectionInput_56\"\r\n"
				+ "																						class=\"rn_SelectionInput rn_SelectionInput rn_Input\">\r\n"
				+ "																						<div\r\n"
				+ "																							id=\"rn_SelectionInput_56_LabelContainer\">\r\n"
				+ "																							<label for=\"rn_SelectionInput_56_Incident.CustomFields.c.physician_oriented\" id=\"rn_SelectionInput_56_Label\" class=\"rn_Label\"><b>O médico prescritor ou de acompanhamento foi informado sobre o caso?</b>                        </label>\r\n"
				+ "																						</div>\r\n"
				+ "																						<select id=\"rn_SelectionInput_56_Incident.CustomFields.c.physician_oriented\" name=\"Incident.CustomFields.c.physician_oriented\">\r\n"
				+ "            <option value=\"\">--</option>\r\n"
				+ "                            <option value=\"243\" >Sim</option>\r\n"
				+ "                    <option value=\"244\" >Não</option>\r\n"
				+ "                    <option value=\"245\" >Não Questionado</option>\r\n"
				+ "                    <option value=\"341\" >NI</option>\r\n"
				+ "                    <option value=\"342\" >NA</option>\r\n"
				+ "                    <option value=\"352\" >Desconhecido</option>\r\n"
				+ "                    <option value=\"353\" >Não Informado</option>\r\n"
				+ "                </select>\r\n"
				+ "																					</div>\r\n"
				+ "																					<div id=\"rn_TextInput_58\"\r\n"
				+ "																						class=\"rn_TextInput rn_Input\">\r\n"
				+ "																						<div\r\n"
				+ "																							id=\"rn_TextInput_58_LabelContainer\">\r\n"
				+ "																							<label for=\"rn_TextInput_58_Incident.CustomFields.Pfizer.PorquePhysicianNaoOrientado\" id=\"rn_TextInput_58_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Especificar o motivo de não informado:</b>                                </label>\r\n"
				+ "																						</div>\r\n"
				+ "																						<input type=\"text\" id=\"rn_TextInput_58_Incident.CustomFields.Pfizer.PorquePhysicianNaoOrientado\" name=\"Incident.CustomFields.Pfizer.PorquePhysicianNaoOrientado\" class=\"rn_Text\" maxlength='200'  />\r\n"
				+ "    </div>\r\n"
				+ "																						<div id=\"rn_SelectionInput_60\"\r\n"
				+ "																							class=\"rn_SelectionInput rn_SelectionInput rn_Input\">\r\n"
				+ "																							<div\r\n"
				+ "																								id=\"rn_SelectionInput_60_LabelContainer\">\r\n"
				+ "																								<label for=\"rn_SelectionInput_60_Incident.CustomFields.c.discussed_health_professional\" id=\"rn_SelectionInput_60_Label\" class=\"rn_Label\"><b>Relator autorizou contato com o médico?</b>                         </label>\r\n"
				+ "																							</div>\r\n"
				+ "																							<select id=\"rn_SelectionInput_60_Incident.CustomFields.c.discussed_health_professional\" name=\"Incident.CustomFields.c.discussed_health_professional\">\r\n"
				+ "            <option value=\"\">--</option>\r\n"
				+ "                            <option value=\"246\" >Sim</option>\r\n"
				+ "                    <option value=\"247\" >Não</option>\r\n"
				+ "                    <option value=\"248\" >Não Questionado</option>\r\n"
				+ "                    <option value=\"343\" >NI</option>\r\n"
				+ "                    <option value=\"344\" >NA</option>\r\n"
				+ "                    <option value=\"354\" >Desconhecido</option>\r\n"
				+ "                    <option value=\"355\" >Não Informado</option>\r\n"
				+ "                </select>\r\n"
				+ "																						</div>\r\n"
				+ "																						<div id=\"rn_TextInput_62\"\r\n"
				+ "																							class=\"rn_TextInput rn_Input\">\r\n"
				+ "																							<div\r\n"
				+ "																								id=\"rn_TextInput_62_LabelContainer\">\r\n"
				+ "																								<label for=\"rn_TextInput_62_Incident.CustomFields.Pfizer.PorqueNaoQuestionarAutorizar\" id=\"rn_TextInput_62_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Especificar o motivo não questionar a autorização de contato:</b>                                </label>\r\n"
				+ "																							</div>\r\n"
				+ "																							<input type=\"text\" id=\"rn_TextInput_62_Incident.CustomFields.Pfizer.PorqueNaoQuestionarAutorizar\" name=\"Incident.CustomFields.Pfizer.PorqueNaoQuestionarAutorizar\" class=\"rn_Text\" maxlength='200'  />\r\n"
				+ "    </div>\r\n"
				+ "																							<div id=\"rn_FieldDisplay_64\"\r\n"
				+ "																								class=\"rn_FieldDisplay rn_Output\">\r\n"
				+ "																								<span class=\"rn_DataLabel\"><b>Nome completo:</b>  </span>\r\n"
				+ "																								<div\r\n"
				+ "																									class=\"rn_DataValue\">\r\n"
				+ "																									T </div>\r\n"
				+ "																							</div>\r\n"
				+ "																							<div id=\"rn_TextInput_66\"\r\n"
				+ "																								class=\"rn_TextInput rn_Input\">\r\n"
				+ "																								<div\r\n"
				+ "																									id=\"rn_TextInput_66_LabelContainer\">\r\n"
				+ "																									<label for=\"rn_TextInput_66_Incident.CustomFields.c.phy_phone_number\" id=\"rn_TextInput_66_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Telefone:</b>                                </label>\r\n"
				+ "																								</div>\r\n"
				+ "																								<input type=\"text\" id=\"rn_TextInput_66_Incident.CustomFields.c.phy_phone_number\" name=\"Incident.CustomFields.c.phy_phone_number\" class=\"rn_Text\" maxlength='40'  />\r\n"
				+ "    </div>\r\n"
				+ "																								<div id=\"rn_TextInput_68\"\r\n"
				+ "																									class=\"rn_TextInput rn_Input\">\r\n"
				+ "																									<div\r\n"
				+ "																										id=\"rn_TextInput_68_LabelContainer\">\r\n"
				+ "																										<label for=\"rn_TextInput_68_Incident.CustomFields.c.phy_email\" id=\"rn_TextInput_68_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>E-mail:</b>                                </label>\r\n"
				+ "																									</div>\r\n"
				+ "																									<input type=\"text\" id=\"rn_TextInput_68_Incident.CustomFields.c.phy_email\" name=\"Incident.CustomFields.c.phy_email\" class=\"rn_Text\" maxlength='80'  />\r\n"
				+ "    </div>\r\n"
				+ "																									<div id=\"rn_TextInput_70\"\r\n"
				+ "																										class=\"rn_TextInput rn_Input\">\r\n"
				+ "																										<div\r\n"
				+ "																											id=\"rn_TextInput_70_LabelContainer\">\r\n"
				+ "																											<label for=\"rn_TextInput_70_Incident.CustomFields.Pfizer.PhysicianOccupation\" id=\"rn_TextInput_70_Label\" class=\"rn_Label\">\r\n"
				+ "        <b>Profissão:</b>                                </label>\r\n"
				+ "																										</div>\r\n"
				+ "																										<input type=\"text\" id=\"rn_TextInput_70_Incident.CustomFields.Pfizer.PhysicianOccupation\" name=\"Incident.CustomFields.Pfizer.PhysicianOccupation\" class=\"rn_Text\" maxlength='60'  />\r\n"
				+ "    </div>\r\n"
				+ "																									</div>\r\n"
				+ "																									<div\r\n"
				+ "																										class=\"cst_WhiteBox\">\r\n"
				+ "																										<div\r\n"
				+ "																											class=\"cst_SubmitBtn\">\r\n"
				+ "																											<div id=\"rn_FormSubmit_71\"\r\n"
				+ "																												class=\"rn_FormSubmit\">\r\n"
				+ "																												<button type=\"submit\" class=\"rn_DisplayButton\" id=\"rn_FormSubmit_71_Button\" disabled>\r\n"
				+ "    Enviar    </button>\r\n"
				+ "																												<span class=\"rn_Hidden\">\r\n"
				+ "        <input id=\"rn_FormSubmit_71_Submission\" type=\"checkbox\" class=\"rn_Hidden\"/>\r\n"
				+ "        <label for=\"rn_FormSubmit_71_Submission\" class=\"rn_Hidden\">&nbsp;</label>\r\n"
				+ "    </span>\r\n"
				+ "																											</div>\r\n"
				+ "																										</div>\r\n"
				+ "																									</div>\r\n"
				+ "					</form>\r\n"
				+ "				</div>\r\n"
				+ "			</div>\r\n"
				+ "		</div>\r\n"
				+ "	</div>\r\n"
				+ "	<script>\r\n"
				+ "		var YUI_config={\"fetchCSS\":false,\"modules\":{\"RightNowTreeView\":\"/euf/core/3.8/js/4.261/min/modules/ui/treeview.js\",\"RightNowTreeViewDialog\":\"/euf/core/3.8/js/4.261/min/modules/ui/treeviewdialog.js\",\"RightNowTreeViewDropdown\":\"/euf/core/3.8/js/4.261/min/modules/ui/treeviewdropdown.js\"},\"lang\":[\"en-US\",\"en-US\"],\"injected\":true,\"comboBase\":\"//azimute--tst1.widget.custhelp.com/ci/cache/yuiCombo/\",\"groups\":{\"gallery-treeview\":{\"base\":\"/rnt/rnw/yui_3.18/gallery-treeview/\",\"modules\":{\"gallery-treeview\":{\"path\":\"gallery-treeview-min.js\"}}}}};\r\n"
				+ "	</script>\r\n"
				+ "	<script type=\"text/javascript\" src=\"/euf/core/3.8/js/4.261/min/RightNow.js\"></script>\r\n"
				+ "	<script type=\"text/javascript\" src=\"/euf/core/3.8/js/4.261/min/RightNow.Chat.js\"></script>\r\n"
				+ "	<script type=\"text/javascript\"\r\n"
				+ "		src=\"/euf/generated/optimized/1654817501/pages/pfizer/ask.df1b404863e985de9380947670780b99.js\"></script>\r\n"
				+ "	<script>\r\n"
				+ "		/* <![CDATA[ */\r\n"
				+ "RightNow.Env=(function(){var _props={module:'standard',coreAssets:'/euf/core/3.8/',yuiCore:'/rnt/rnw/yui_3.18/',profileData:{\"isLoggedIn\":true,\"previouslySeenEmail\":null,\"contactID\":19776,\"socialUserID\":null,\"firstName\":\"Vinicius Santos\",\"lastName\":\"NI\",\"email\":\"vinisantos@gmail.com\"}};return function(prop){return _props[prop];};})();RightNow.Interface.setMessagebase(function(){return {\"ATTRIBUTES_LC_LBL\":\"attributes\",\"ATTRIBUTE_HAVENT_SPECIFIED_VALID_IT_LBL\":\"  Value for '%s' attribute is a number and you haven't specified a valid value for it.\",\"BACK_LBL\":\"Back\",\"BEG_DIALOG_PLS_DISMISS_DIALOG_BEF_MSG\":\"Beginning of dialog, please dismiss dialog before continuing\",\"CHANGED_LBL\":\"Changed\",\"CLOSE_CMD\":\"Close\",\"COL_SAVE_ED_ERR_L_INV_E_PERMISSIONS_MSG\":\"Widget changes could not be saved due to errors while saving. Please check the file permissions.\",\"DIALOG_LBL\":\"dialog\",\"DIALOG_PLEASE_READ_TEXT_DIALOG_MSG_MSG\":\"dialog, please read above text for dialog message\",\"END_DIALOG_PLS_DISMISS_DIALOG_BEF_MSG\":\"End of dialog, please dismiss dialog before continuing\",\"ERROR_LBL\":\"Error\",\"ERRORS_LBL\":\"Errors\",\"ERROR_PCT_S_LBL\":\"Error: %s\",\"ERROR_REQUEST_ACTION_COMPLETED_MSG\":\"There was an error with the request and the action could not be completed.\",\"ERR_SUBMITTING_FORM_DUE_INV_INPUT_LBL\":\"There was an error submitting the form due to invalid input\",\"ERR_SUBMITTING_SEARCH_MSG\":\"There was a problem with your request.  Please change your search terms and try again.\",\"HELP_LBL\":\"Help\",\"INFORMATION_LBL\":\"Information\",\"INFORMATION_S_LBL\":\"Information: %s\",\"OK_LBL\":\"OK\",\"PCT_S_ATTRIB_REQD_HAVENT_VALUE_MSG\":\"The '%s' attribute is required and you haven't specified a value for it.\",\"PG_COL_SAVE_ED_ERR_L_INV_E_PERMISSIONS_MSG\":\"Widget changes of page could not be saved due to errors while saving. Please check the page file permissions.\",\"REVEALED_DISP_TB_DD_OP_ADDTL_T_EXPOSED_MSG\":\"Note: The widget, when revealed, can be inspected, but you may need to perform additional actions for it to be exposed.\",\"SOME_INST_ID_BUT_SEE_ITS_SATTRIBUTESS_MSG\":\"Some or all instances of this widget are hidden, but you can see its %sattributes%s.\",\"SUCCESS_S_LBL\":\"Success: %s\",\"TEMPL_COL_SAVE_ED_ERR_INV_TEMPL_PRMSSNS_MSG\":\"Widget changes of template could not be saved due to errors while saving. Please check the template file permissions.\",\"THIS_WIDGET_HAS_NO_ATTRIBUTES_MSG\":\"This widget has no attributes.\",\"THIS_WIDGET_HAS_NO_VIEW_LBL\":\"This widget has no view\",\"VAL_PCT_S_ATTRIB_MINIMUM_VAL_ACCD_MSG\":\"Value for '%s' attribute is too small. The minimum value accepted is %s but the value received was %s.\",\"VAL_PCT_S_ATTRIB_MAX_VAL_ACCD_PCT_S_MSG\":\"Value for '%s' attribute is too large. The maximum value accepted is %s but the value received was %s.\",\"VIEW_ATTRIBUTES_LBL\":\"View Attributes\",\"WARNING_LBL\":\"Warning\",\"WARNING_S_LBL\":\"Warning: %s\",\"WIDGET_CHANGES_ERRORS_WILL_IGNORED_MSG\":\"Widget changes with errors will be ignored.\",\"FORMSUBMIT_PLACED_FORM_UNIQUE_ID_MSG\":\"FormSubmit must be placed within a form with a unique ID.\",\"PLS_VERIFY_REQ_ENTERING_TEXT_IMG_MSG\":\"Please verify your request by entering the text in the image.\",\"VALUE_MUST_BE_AN_INTEGER_MSG\":\"value must be an integer\",\"VALUE_IS_TOO_LARGE_MAX_VALUE_MSG\":\"value is too large (max value: \",\"VALUE_IS_TOO_SMALL_MIN_VALUE_MSG\":\"value is too small (min value: \",\"CONTAIN_1_CHARACTER_MSG\":\"must contain at least 1 more character\",\"PCT_D_CHARACTERS_MSG\":\"must be at least %d characters long.\",\"EXCEEDS_SZ_LIMIT_PCT_D_CHARS_1_LBL\":\"exceeds its size limit of %d characters by 1 character\",\"S_SZ_CHARS_CHARS_CHARS_XP_SBM_SZ_XCDD_MSG\":\"exceeds its size limit of %d characters by %d characters. Note that some characters (such as '&' and '<') are expanded upon submission which may cause the size limit to be exceeded.\",\"PCT_S_IS_AN_INVALID_POSTAL_CODE_MSG\":\"%s is an invalid postal code\",\"PCT_S_IS_AN_INVALID_PHONE_NUMBER_MSG\":\"%s is an invalid phone number\",\"PCT_S_CONT_SPACES_DOUBLE_QUOTES_LBL\":\"%s cannot contain spaces, double quotes or <>\",\"PCT_S_DIDNT_MATCH_EXPECTED_INPUT_LBL\":\"%s didn't match expected input\",\"CONTAIN_SPACES_PLEASE_TRY_MSG\":\"must not contain spaces. Please try again.\",\"PCT_S_IS_INVALID_MSG\":\"%s is invalid\",\"IS_NOT_A_VALID_URL_MSG\":\"is not a valid URL\",\"REQUIRED_LBL\":\"Required\",\"FIELD_REQUIRED_MARK_LBL\":\"*\",\"THERE_PROB_REQ_ACTION_COULD_COMPLETED_MSG\":\"There was a problem with the request and the action could not be completed.\",\"ERROR_PAGE_PLEASE_S_TRY_MSG\":\"There is an error on the page. Please correct the problem(s) and try again.\",\"THUMBNAIL_FOR_ATTACHED_IMAGE_MSG\":\"Thumbnail for attached image.\",\"PCT_S_IS_NOT_COMPLETELY_FILLED_IN_MSG\":\"%s is not completely filled in\",\"PCT_S_IS_NOT_A_VALID_DATE_MSG\":\"%s is not a valid date\",\"VALUE_MIN_VALUE_PCT_S_MSG\":\"value is too small (min value: %s)\",\"PCT_S_REQUIREMENTS_MET_LBL\":\"%s requirements have not been met\",\"PASSWD_VALIDATION_REQS_READ_L_MSG\":\"For password validation requirements, read the list below.\",\"PASSWORD_IS_TOO_SHORT_MSG\":\"Password is too short\",\"PERFECT_LBL\":\"Perfect\",\"PASSWORD_IS_TOO_INSECURE_MSG\":\"Password is too insecure\",\"COMPLETE_LBL\":\"Complete\",\"INCOMPLETE_LBL\":\"Incomplete\",\"EXPECTED_INPUT_LBL\":\"Expected Input\",\"WAITING_FOR_CHARACTER_LBL\":\"Waiting for character: ' \",\"PLEASE_TYPE_A_NUMBER_MSG\":\"Please type a number\",\"PLEASE_ENTER_UPPERCASE_LETTER_MSG\":\"Please enter an uppercase letter or a number\",\"PLEASE_ENTER_AN_UPPERCASE_LETTER_MSG\":\"Please enter an uppercase letter\",\"PLS_ENTER_UPPERCASE_LETTER_SPECIAL_MSG\":\"Please enter an uppercase letter, a number or a special character\",\"PLEASE_ENTER_LOWERCASE_LETTER_MSG\":\"Please enter a lowercase letter or a number\",\"PLEASE_ENTER_A_LOWERCASE_LETTER_MSG\":\"Please enter a lowercase letter\",\"PLS_ENTER_LOWERCASE_LETTER_SPECIAL_MSG\":\"Please enter a lowercase letter, a number or a special character\",\"PLEASE_ENTER_A_LETTER_OR_A_NUMBER_MSG\":\"Please enter a letter or a number\",\"PLEASE_ENTER_A_LETTER_MSG\":\"Please enter a letter\",\"PLEASE_ENTER_LETTER_SPECIAL_CHAR_MSG\":\"Please enter a letter, a number or a special character\",\"THE_INPUT_IS_TOO_LONG_MSG\":\"The input is too long\",\"THE_INPUT_IS_TOO_SHORT_MSG\":\"The input is too short\",\"CHARACTER_LBL\":\"Character\"};});\r\n"
				+ "RightNow.Interface.setConfigbase(function(){return {\"DE_VALID_EMAIL_PATTERN\":\"^((([-_!#$%&'*+\\/=?^~`{|}\\\\w]+(\\\\.[.]?[-_!#$%&'*+\\/=?^~`{|}\\\\w]+)*)|(\\\"[^\\\"]+\\\"))@[0-9A-Za-z]+([\\\\-]+[0-9A-Za-z]+)*(\\\\.[0-9A-Za-z]+([\\\\-]+[0-9A-Za-z]+)*)+[; ]*)$\",\"CP_HOME_URL\":\"home\",\"CP_FILE_UPLOAD_MAX_TIME\":300,\"OE_WEB_SERVER\":\"azimute--tst1.custhelp.com\",\"SUBMIT_TOKEN_EXP\":30,\"CHAT_CLUSTER_POOL_ID\":\"\"};});\r\n"
				+ "RightNow.Url.setParameterSegment(5);\r\n"
				+ "RightNow.Interface.Constants = \r\n"
				+ "{\"API_VALIDATION_REGEX_EMAIL\":\"((([-_!#$%&'*+\\/=?^~`{|}\\\\w]+([.][-_!#$%&'*+\\/=?^~`{|}\\\\w]*)*)|(\\\"[^\\\"]+\\\"))@[0-9A-Za-z]+([\\\\-]+[0-9A-Za-z]+)*(\\\\.[0-9A-Za-z]+([\\\\-]+[0-9A-Za-z]+)*)+[;, ]*)+\",\"EUF_DT_DATE\":1,\"EUF_DT_DATETIME\":2,\"EUF_DT_INT\":5,\"EUF_DT_RADIO\":3};\r\n"
				+ "YUI().use('event-base',function(Y){Y.on('domready',function(){var n=RightNow.namespace,W=RightNow.Widgets,c='createWidgetInstance';\r\n"
				+ "n('RightNow.Widgets.TextInput').templates={\"label\":\"<% if (label) { %>  <label for=\\\"rn_<%= instanceID %>_<%= fieldName %>\\\" id=\\\"rn_<%= instanceID %>_Label\\\" class=\\\"rn_Label\\\" aria-hidden=\\\"true\\\"> <%= label %> <% if (required) { %>  <%= getRequiredLabel() %>  <% } %> <\\/label> <% } %>\",\"labelValidate\":\"<label for=\\\"rn_<%= instanceID %>_<%= fieldName %>_Validate\\\" id=\\\"rn_<%= instanceID %>_<%= fieldName %>_LabelValidate\\\" class=\\\"rn_Label\\\"><%= label %><% if (required) { %>  <%= getRequiredLabel() %> <% } %><\\/label>\"};\r\n"
				+ "n('RightNow.Widgets.SelectionInput').templates={\"label\":\"<% if (label) { %>  <label for=\\\"rn_<%= instanceID %>_<%= fieldName %>\\\" id=\\\"rn_<%= instanceID %>_Label\\\" class=\\\"rn_Label\\\"> <%= label %> <% if (required) { %>  <%= getRequiredLabel() %>  <% } %> <% if (hint) { %> <span class=\\\"rn_ScreenReaderOnly\\\"><%= hint %><\\/span> <% } %> <\\/label> <% } %>\",\"legend\":\"<% if (label) { %>  <%= label %> <% if (required) { %>  <%= getRequiredLabel() %>  <% } %> <% } %>\"};\r\n"
				+ "n('RightNow.Widgets.FormSubmit').requires=[\"anim-scroll\"];\r\n"
				+ "W.setInitialWidgetCount(27);\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":12},\"a\":{\"label_input\":\"<b>Descri\\u00e7\\u00e3o do Relato:<\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.AzimutePTC.Narrativa\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.AzimutePTC.Narrativa\",\"custom\":false,\"constraints\":{\"minLength\":1,\"maxLength\":1048576,\"maxBytes\":1048576},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVoNGY0OHN4bzlwRkR0aW9mYmI5b2QzT3lxbU1WalRnb3FZYkJUWGVVd1NyeUp5enlsMmFxcjRBYmpnQ0RqfmR4NnZsNUZzbHJfUjdRdTZ6N1dnNVI4d0FMVmpTRkNOWEliU2x2c05oMHNMVlFLZlY0TDh2amxRd25tajZobGM0THpsS2JtYXZ2emJRRVo4RmY0NnZiNVo3QjA3YW5aRTl2\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5EZXNjcmlcdTAwZTdcdTAwZTNvIGRvIFJlbGF0bzo8XC9iPiIsIm5hbWUiOiJJbmNpZGVudC5DdXN0b21GaWVsZHMuQXppbXV0ZVBUQy5OYXJyYXRpdmEifSwiZXhlbXB0X2Zyb21fbG9naW5fcmVxdWlyZW1lbnQiOnsiZXhpc3RpbmdDb250YWN0Q2hlY2siOnRydWV9fQ==','fUTsZPfvEbbIpe97anrr41imH0q1IXh2zmb6HUFyXJvWeOa_cyrelYsU2VdFli0ECjTpECe39_BQWGQ4xN5K8wivpLrESmgr7XpQR6a1HNFGYQN3vKvAdTvRRPQCK4bQTJ3xg3105WRqU!',1655754697,'TextInput_12','standard/input/TextInput','RightNow.Widgets.TextInput','12','ZlVmdUNSa2RKQ0x4NldhclhOaHQ2eVZsYXMySjlMNE04VXBmbFI3YXU5Zno0OTJPNEdfV1J4czR5fkV6aWVSWnF_NjlMYVdXMWd0S1RRN01hbTdLU2FSNjRRQmFaUm5rbEFMRjhfaEZMNmNBVkRIRHVYQTFoTDN3NG9lWG5POU9WMThnY0pZUk5jeFFsZEd4fjAzU29xMVVDMVZSQ3BEQmlr');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":14},\"a\":{\"label_input\":\"<b>Em caso de uso na gesta\\u00e7\\u00e3o, data prevista para o parto:<\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.Azimute.DtEstimadaParto\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.Azimute.DtEstimadaParto\",\"custom\":false,\"constraints\":{\"minLength\":1,\"maxLength\":10},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlU0Qzd2YTJzZkxwMlRzcDczNUliMHhLbXVmUFBvVzhqc2Z6fktIYmt_ZmlTNnZWVWVuZktSRm1LcEpYMUh_TF9xOHJ2fmZOc3JkR3hkS0Zma0hJSEIzdzA1czF0ZXlvRFNndmFrcExZWWY3ZzhiV0hpa09oYkJkcERKQ3NoMGVmWUVoRXNWdE02QWNtZXRLeGhjT0RRdjl4c2NnUFJuRTNQ\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5FbSBjYXNvIGRlIHVzbyBuYSBnZXN0YVx1MDBlN1x1MDBlM28sIGRhdGEgcHJldmlzdGEgcGFyYSBvIHBhcnRvOjxcL2I+IiwibmFtZSI6IkluY2lkZW50LkN1c3RvbUZpZWxkcy5BemltdXRlLkR0RXN0aW1hZGFQYXJ0byJ9LCJleGVtcHRfZnJvbV9sb2dpbl9yZXF1aXJlbWVudCI6eyJleGlzdGluZ0NvbnRhY3RDaGVjayI6dHJ1ZX19','fUXXAcqKP56kx8FlXg89wCs33LksJrWPnNE64wc0e3holTwrXIJbGpCyNgrtDxBR2ztULxGwt3aj3gsx1wfKbRi8E0yYTm75gWlTzUNaimGxhXkTrVhWF0gShsREeod8A5GTwApV28Uug!',1655754697,'TextInput_14','standard/input/TextInput','RightNow.Widgets.TextInput','14','ZlU1T2ZHVXpRalh3VXF_N0xXQjZmVGRSYjZQeHlJTWVOVWptODBHczZlMTBTajBWVEEzcTRTZX5xWDV5eG5CYTZjZ21HQ1lTVHp4TzBua2R_OXNzOUtrcXlVOENxfjEyMTdRUEVPanBzTE1tdU1FMkVOdnhWR0RXSjZ1ZVBNNWlBcWM0TjU3TkdCaUJqY1Bjb2VLV2E4cDFTUXhOSnZ4a0tJ');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":16},\"a\":{\"label_input\":\"<b>Data de conhecimento da informa\\u00e7\\u00e3o: <\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.dt_day0\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.dt_day0\",\"custom\":true,\"constraints\":{\"maxLength\":18},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVkUERDTlRMX0Z_bEN0UkVEdDNPOHg4T2FVekR1VzNSOEZzOVdMN0JPNHhvVjF4Z2tqelVSRXRpUkQ4eFBDRXJpRmM3YVRKYTVZWDR3OVBZSVV2OGFDYWlJQ2x6akswRlVYa1VZQ0xjUmVfOVh4d1Y5fktJMzI1NVdnVDJTdjJlWlBpOG5Fc1NuYmcwUnRreVozVjlGRHplc2E4UmQwVV9V\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5EYXRhIGRlIGNvbmhlY2ltZW50byBkYSBpbmZvcm1hXHUwMGU3XHUwMGUzbzogPFwvYj4iLCJuYW1lIjoiSW5jaWRlbnQuQ3VzdG9tRmllbGRzLmMuZHRfZGF5MCJ9LCJleGVtcHRfZnJvbV9sb2dpbl9yZXF1aXJlbWVudCI6eyJleGlzdGluZ0NvbnRhY3RDaGVjayI6dHJ1ZX19','fU1jy9LL2XFTQVakaLB0lVv4sY_BgTddomz5tBg07Lf2wmkJO4fUgTUUGmvbOXMfq7oLvhORHxpkq6C5XaAiBmGvDeN1HSh7H_24bNT7oRFcyLa6B59dkytGjLYRPT3NDsbYjCs_FwAGs!',1655754697,'TextInput_16','standard/input/TextInput','RightNow.Widgets.TextInput','16','ZlU1TGdtYXZtZ25abmRMSkxPOGJkcnVUTGV5X3BFbkpSX3hiUEhpcXU0TEkwTzMzbGhtRzlEU35JS01ONDF3M1JvWXlPV2U3M0Z3cl9kZnUzQXpZdmlIOEI3TktNVzVaQ25TS19OUERMZmRyZEVXM1RTSTRHMUdYc1VHcE9ndTlDT2MzZmt_V01UanVOMDNhbGh1UFpUNHZXc242ZmpjVkJO');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":22},\"a\":{\"label_input\":\"<b>Idade: <\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.pat_dob\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.pat_dob\",\"custom\":true,\"constraints\":{\"maxLength\":20},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVxbXdmbXpjY1JHV0dROTZwUVdIaUUyQ2pJMWNpMGI4cjRzVkhlfkdrdWZ4RUY4ODFuTmJQcVNlVkVCYzZnfkt3UEdCMUQzRU81RzBGeWtid3hjR1ZjaXJieXFhRH5mN191SkhmWENxcnVPVFJwYjIwTktqZHhSV21lMkxNfkhmQVhPY1ZUWjN6b3BzWUcySnh4MUVoajIzeDQ2ZEhGV0RM\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5JZGFkZTogPFwvYj4iLCJuYW1lIjoiSW5jaWRlbnQuQ3VzdG9tRmllbGRzLmMucGF0X2RvYiJ9LCJleGVtcHRfZnJvbV9sb2dpbl9yZXF1aXJlbWVudCI6eyJleGlzdGluZ0NvbnRhY3RDaGVjayI6dHJ1ZX19','fU26yL~wbaCLm2DQBcthMjZebYEzqOvulsG7HH71zQQ~MYV63sUCQy6sxVvKiIG3W5rIhMV5d2FlNLUinjzt4Fm3Orm5CbVELE0YZb4v14esFFYVNP88RHfCNXmb45u7uYoFilI1oafL4!',1655754697,'TextInput_22','standard/input/TextInput','RightNow.Widgets.TextInput','22','ZlVmN3JveWhJa0NDWlh_OUZrQzBtYzZleWQwMVhwV3NGRHZCNk53U1pnRFVJS2hYMEtlN3NaMlJiMFRNaDdrRGxrU21SUEFScnF6clRJVU9sSVhwNEQzWGpDSDZwTkJJXzBFU1BtQmFzNlVuVn5jaWc2a2NEa0kwUE1EWWhMcmJDaU5TV1A5NlF2WmcxZlZjT3pqWVFZUmVCQUlWflVVVnZF');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":26},\"a\":{\"label_input\":\"<b>Outro Produto (Se houver): <\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.product_name\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.product_name\",\"custom\":true,\"constraints\":{\"maxLength\":60},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVudVZCdjhlSlpyc0Y3RXNTRW05YVVlRVBvVnBDUVBHTVhaWWMydERzVWNBSHJZWmt1M3VuNFUwSjI4S3pJQ2hqWnpCQ3VXUUZZemo0elB3c2JOVERrYWJ1NExUSTJMenluRER3cmxwOE13RXBlbXlCTkQ4eW1HX0Q3Vl91WTF0T2EwVk9nbEF1dEF3cUM3U3FmckVjYzhYMlVCdVpETjl0\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5PdXRybyBQcm9kdXRvIChTZSBob3V2ZXIpOiA8XC9iPiIsIm5hbWUiOiJJbmNpZGVudC5DdXN0b21GaWVsZHMuYy5wcm9kdWN0X25hbWUifSwiZXhlbXB0X2Zyb21fbG9naW5fcmVxdWlyZW1lbnQiOnsiZXhpc3RpbmdDb250YWN0Q2hlY2siOnRydWV9fQ==','fUC~l0NfHYd4qsnLp5t78BgZ~0Du~UQ9HseuXjyxB_SdcTb0qdgxVLJ6n4_s0iyAaedAwxW7KmKwxBQnhit7nLl8lNX1uOOwoX4BZWGn8b~2s6KHX4AVSwch0XaR5LP6JyMj~a6PVgWiA!',1655754697,'TextInput_26','standard/input/TextInput','RightNow.Widgets.TextInput','26','ZlV_TjdTQ1Rnc2NVTndsOHliMXZJUFBHS21LcXRZZTF0Wk5WflYwclZUNWFJdWJaajk1ODhidmc2fkhOZ3B1OW56YzFCN18weEQ3SGc1YmZMa0dGYjhJQzA3NUtpc1o3OFB1ME5CVDdVb2I2cVd6c1RDdUlIdURFaFZmTFhrYk84WWF5dW96amxjaDVfMWptUGZsdURmMVVhNWs1dm5SSElZ');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":28},\"a\":{\"label_input\":\"<b>Especificar apresenta\\u00e7\\u00e3o: <\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.prod_route_administration\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.prod_route_administration\",\"custom\":true,\"constraints\":{\"maxLength\":40},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVXeFFYcDJZQ0hINFdpbzZSa2V5TWxQVTRTQ1pkdEtFUH5VR3hmUGFJbTl0UEpTUTRRbkpkVEJJTlYyeUpXd1cxTTFHM29_cnUzZUUwdThYVmJoMjJEcTF6QjNNZnNEN0oxTlBNflB6QzNGcFpmaXJlR1dGTTRCQ0szUmFDMkdsZjlRVzRJZlo2UzJuNTh6Qzc0MTFoMEdXX0hHWGw0S2NW\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5Fc3BlY2lmaWNhciBhcHJlc2VudGFcdTAwZTdcdTAwZTNvOiA8XC9iPiIsIm5hbWUiOiJJbmNpZGVudC5DdXN0b21GaWVsZHMuYy5wcm9kX3JvdXRlX2FkbWluaXN0cmF0aW9uIn0sImV4ZW1wdF9mcm9tX2xvZ2luX3JlcXVpcmVtZW50Ijp7ImV4aXN0aW5nQ29udGFjdENoZWNrIjp0cnVlfX0=','fUBSSKYPmmNS23HsG7T61h5rOxrt3UZ8tkfN_7zIXGSPb8kSlef2Vzoy9dFtYp8cWksUaF1htSLykKpZ_kzWk2MAaBtElu_XInLWUufqUeTe2WAMCkBWjacbxA3LmiVCh2POXIVBqMVZk!',1655754697,'TextInput_28','standard/input/TextInput','RightNow.Widgets.TextInput','28','ZlVMb05oM0RBeDBLeFNaakRZOG1YeHZ_RmR_a2swaW5oOWVPSlk1RVozVXlmMHhuWEE4TVdfY1RMVVdkWkJmQ04yaDQ0NkVvUU9QOHhGaGo3cU9Pc0I2SFVCXzM5N2h1akhGVXYxT3k1WHMwandHZm9oOFAxR052X2xneDFhY21TMkZxU1hiSzdxbmQ4MklPUXFEejJ1aEV1bUoxYjlWMDJr');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":30},\"a\":{\"label_input\":\"<b>Data de In\\u00edcio do Tratamento: <\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.prod_dt_onset\",\"required\":false,\"hint\":\"Therapy Start Date\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.prod_dt_onset\",\"custom\":true,\"constraints\":{\"maxLength\":18},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVLX3YxeXNQNTRoRFZlQnNEZ3FmdWpoZ01zZnl2MzZtN0lnRWhsSlV4VHZ2UEc5emFLQjhsZkxHZnRhYUdocm5IM1BTU0xIanNPTm9XOHFXR0JkT3IwTGtIdEtjbjNndDNJWDZ3dFpxQ2ZTMHVjc2pLX3BSVTlOVjFKYnJhWnZ6aHI2RjdZdDN4dlZEVmNqM2pBNUdQYmdHTVZ2UXQzaGE0\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5EYXRhIGRlIEluXHUwMGVkY2lvIGRvIFRyYXRhbWVudG86IDxcL2I+IiwibmFtZSI6IkluY2lkZW50LkN1c3RvbUZpZWxkcy5jLnByb2RfZHRfb25zZXQifSwiZXhlbXB0X2Zyb21fbG9naW5fcmVxdWlyZW1lbnQiOnsiZXhpc3RpbmdDb250YWN0Q2hlY2siOnRydWV9fQ==','fUpFdHfrBTjW942RS4bc9Qy9FOMghwbtCd8WyhxHIo86j~cHef30mkvyHTtOsn2Ovdrwdo9lw2z_Z3LNawxJzZOvEe2A0Ni2w6L~TaO80aFcIvszI06LTcuO5c68YEylEnw9GBHW8CJlk!',1655754697,'TextInput_30','standard/input/TextInput','RightNow.Widgets.TextInput','30','ZlVKbFI3UkRQVmxPQjZIZjRjbWRfSV9IOXpqMGFOVk5mS292OUZkNFhQVnVtYmwya2k3OHJyVlBRdlU2djZvZjM0d1RtdHhhM3dqVXJMWEUyNUV2UGlEaGV6SWo1ZXUxREtoR2Y4eDV4OTRCa3dmU0N5eHZFbWo5Tk1TRGxtbXZpckw5OFJUdDljcVhBbk45c0dLWndHTWZTS0wxRUFGSGNQ');\r\n"
				+ "W[c]({\"i\":{\"c\":\"SelectionInput\",\"n\":\"SelectionInput\",\"w\":32},\"a\":{\"hidden_items\":\"79,80\",\"label_input\":\"<b>Paciente em tratamento: <\\/b>\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.prod_therapy_interrupted\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"initial_focus\":false,\"validate_on_blur\":false,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"display_as_checkbox\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"selection\"},\"j\":{\"type\":\"NamedIDLabel\",\"name\":\"Incident.CustomFields.c.prod_therapy_interrupted\",\"custom\":true,\"constraints\":[],\"mask\":null,\"readOnly\":false}},'W10=','fU4Lkf390E5PiLmIDepSmX3n31sYoqFiWmLqLkDVzlMTE~5MYYRbUqwtny1xk~Kjvj05peUnMIRV9akMQGABEdSbGi2obGFrAu~hKa_g1N5l31uP_bsw9DW_1j6W60tZSoioGI0~hEyqo!',1655754697,'SelectionInput_32','','RightNow.Widgets.SelectionInput','32','ZlVEQXBOQ2p6WTMzRGp3SHljUWtkVk1XRXZQWFJMc0YzeE1EX1BvT1RCWUNFeDV6dFRmd2NuTzZiczlqeUNmSUFLWkFsRnVmSlhQZWZBaG9JaDVQUkdIZ0RKN2ppdFAzSFBmMmNydGh4RkN1UFQwdkpMM2xROUdPb2xWUmpSVE9tNWpMSHVCQ0NBdVhVdHJUZHZfczZrM1V3eTMwT3lPRXZi');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":34},\"a\":{\"label_input\":\"<b>Data de T\\u00e9rmino do Tratamento: <\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.therapy_stop_dt\",\"required\":false,\"hint\":\"Outcome Therapy Date\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.therapy_stop_dt\",\"custom\":true,\"constraints\":{\"maxLength\":18},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlUzUkpUWml3aGxfOHhqSXMzNlR2dFFwdm9CNXllelRvX3ZxTW1aN19pZ1Z3bmVnU3NYNUd2WHpxSGQ4aURVczBqXzRXaH5RWEpaa0dIengxMmRjWmJwTVV_X0VDM0RaVUpIbkpIRERiZHFYdnJVYmZqRm96M1JmTFBLcXVlNVJTT2hfa3FvM3pXUnViNEpMT0dmbDZvVFN3dklqUGJaMmRn\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5EYXRhIGRlIFRcdTAwZTlybWlubyBkbyBUcmF0YW1lbnRvOiA8XC9iPiIsIm5hbWUiOiJJbmNpZGVudC5DdXN0b21GaWVsZHMuYy50aGVyYXB5X3N0b3BfZHQifSwiZXhlbXB0X2Zyb21fbG9naW5fcmVxdWlyZW1lbnQiOnsiZXhpc3RpbmdDb250YWN0Q2hlY2siOnRydWV9fQ==','fU79Y32FzBoMlSnP0Eg3VU93efzC7bfFraZJf7Z20BbGS2oTUHzqWUjarIl4SuiUasR_ek~Q4UbCkQFaW_uHPe~7V2v4wVzS~u0muXiULhq3synT7v0Anu8GjuQQxlIebMaKDQgbcoZ4A!',1655754697,'TextInput_34','standard/input/TextInput','RightNow.Widgets.TextInput','34','ZlVxSW16X2lQV3RueXNWb1RKMEdmN1duTHpyZnl5Q3NQYUFtR3djS20xTzlzbHFOVGxpbjVBejY0NWk4NlhhbUhaMkRJOVMzenUwRVh3ZTRlclRWalQ3ZGFTVWoyVGh2N0Q0SGs1OFRvX1JfVnh0NDYzZ3VEWG9qYjZaflpScjBHV2FZanF5cExGckhfNHFkWGx_fms3eWFwS0dYWWJqc2tt');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":36},\"a\":{\"label_input\":\"<b>Lote: <\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.prod_batch_number\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.prod_batch_number\",\"custom\":true,\"constraints\":{\"maxLength\":40},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVEQlhVdVBOaFp4NUFzTUQyNHBTWkpsNmhKX2lMZHdfeUN0MEhFbVB4bTY5NTJ_Q0g0MU5SV0d2Q3NWRllFN2RISzZtazB1R2dpTHpuTmhWbzdNbWMwY3Frc0J5dlVWU25IV25_R3JMeko3SHhafjZUemtTQTFmUERhS3V1WmxreG5XbEI0VkhUNHludk9nSG1ZbWhCT1lEaDZlUzJBMUZG\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5Mb3RlOiA8XC9iPiIsIm5hbWUiOiJJbmNpZGVudC5DdXN0b21GaWVsZHMuYy5wcm9kX2JhdGNoX251bWJlciJ9LCJleGVtcHRfZnJvbV9sb2dpbl9yZXF1aXJlbWVudCI6eyJleGlzdGluZ0NvbnRhY3RDaGVjayI6dHJ1ZX19','fUCPr7PdsFq591jgfN61atlnHEM3EPZruUEfO8pJlJEnu6KfKhX6oLf~sP6lXbdHxW976bJRzLnAbiRBJUK4CVNxqs4y~~hfb9xWRXisHycL6R9oBZK~AMEZZ6pMIVkJgw3wfIyKeUkz0!',1655754697,'TextInput_36','standard/input/TextInput','RightNow.Widgets.TextInput','36','ZlVCbmRLYXlEc1k4eWxQQzhjbTJ2eDlXOUJnTk9IbmV6STVzMnhSQlliZWFacmNza2hLcmJMX2xhYzJHRTZsMVJaZnNpdVJPN3VkVmVjWHdEX3hmS3phOXd2YTk4VjhvYWg1Q1d3YVhnOVBJZ1hrZW5SX0NZcUIwN1VGczlDdm41QTd5aX5UTlBMX1RGaFlEbmJsSGNwdjBfTFNGUFA1WnJm');\r\n"
				+ "W[c]({\"i\":{\"c\":\"SelectionInput\",\"n\":\"SelectionInput\",\"w\":38},\"a\":{\"hidden_items\":\"\",\"label_input\":\"<b>Se n\\u00e3o houver, informar o motivo:<\\/b>\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.Pfizer.MotivoNaoLote\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"initial_focus\":false,\"validate_on_blur\":false,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"display_as_checkbox\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"selection\"},\"j\":{\"type\":\"Menu\",\"name\":\"Incident.CustomFields.Pfizer.MotivoNaoLote\",\"custom\":false,\"constraints\":[],\"mask\":null,\"readOnly\":false}},'W10=','fUglrdfYUUvq6t_CF3B1me1jon3GCdbmUs9MNlwkxfQ~f49slfiQhCgkeG15N~n7FGbjPp9mkCpfVJ3GLxQYPlqUazixWDGLhFMXn1tn12xqeWmXhlzx9rM1kTGR9RLVliziS~gK6xPbY!',1655754697,'SelectionInput_38','','RightNow.Widgets.SelectionInput','38','ZlU1MlNiT3AzUVZZYnRnc3oweWR6RWdHb2F5TjRqT0VUdGphcHdwY1NvUHNSZzNjTzBETkhxQTNDYVd1MGZCZkVUMU9pRncyY0trMERMSkxRRGF3R3Zub3BnenBsdlhtSDVFbVBtb3VhUzhrb2htekpkcGhCcExzY2RNU25TVFVXSEpHd3VnZTZWVVRzVn5yd0J_Vm03STNFOFdTc05sSHlS');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":40},\"a\":{\"label_input\":\"<b>Especificar o motivo de n\\u00e3o informa\\u00e7\\u00e3o do lote:<\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.Pfizer.OutroMotivoNaoLote\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.Pfizer.OutroMotivoNaoLote\",\"custom\":false,\"constraints\":{\"minLength\":1,\"maxLength\":150},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVFNmJoSkxafnR2YXNkYjJOQ193anBtSGhUY2t3UFozUjBnSVJjeEJnYUZISjJZdUQ2dUFhfjZobzRYMUsxU3NWVEFfenFyMFBaZ2JVMnRDQzNfREFmVFFPQzJNR1Noc0t_SDJBaWJOMng4RTRPRE9xeXg4Mm9raUh_ZGRaODc4S0hld2NPV1NBeXZiRUhIMVZnMDZjd19YVEZqUjJ3SFJJ\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5Fc3BlY2lmaWNhciBvIG1vdGl2byBkZSBuXHUwMGUzbyBpbmZvcm1hXHUwMGU3XHUwMGUzbyBkbyBsb3RlOjxcL2I+IiwibmFtZSI6IkluY2lkZW50LkN1c3RvbUZpZWxkcy5QZml6ZXIuT3V0cm9Nb3Rpdm9OYW9Mb3RlIn0sImV4ZW1wdF9mcm9tX2xvZ2luX3JlcXVpcmVtZW50Ijp7ImV4aXN0aW5nQ29udGFjdENoZWNrIjp0cnVlfX0=','fUd0_pRQN2sp0s0ZGtuZKyDduE1hC23A_lmSs5Z4xyBNFv864Tb4ow7gaQ6HLl09AOjA4~cLNlyFP8if2rkKYcuUgVzFvTmOHsjldp2wEKcFV9iB2PnIzsi1btEzN3V4g5DvvulUIgIIA!',1655754697,'TextInput_40','standard/input/TextInput','RightNow.Widgets.TextInput','40','ZlVXMjRCTHh5UWpTZjFPQ3o3UVRaSlF0YVBtcWNGZFJxV1dvSVk1UzFwc2R0WWFIc3hqVzdoZmFVbWJPcWgzOWo3S0NreXBEc1hJQzZldVFZSkgwZEJRbklEczNHU3RoekhBZGZGd20xWk4wcGoyeGxzU2ozOGpnclE2NEV5OEROengwVWVjSEhVMGdjMUc3RWZjdE5iUFdSemxobVNRSF9Q');\r\n"
				+ "W[c]({\"i\":{\"c\":\"SelectionInput\",\"n\":\"SelectionInput\",\"w\":42},\"a\":{\"hidden_items\":\"50,51,52,53\",\"label_input\":\"<b>Autoriza contato do departamento respons\\u00e1vel, se necess\\u00e1rio? <\\/b>\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.reporter_allow_contact\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"initial_focus\":false,\"validate_on_blur\":false,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"display_as_checkbox\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"selection\"},\"j\":{\"type\":\"NamedIDLabel\",\"name\":\"Incident.CustomFields.c.reporter_allow_contact\",\"custom\":true,\"constraints\":[],\"mask\":null,\"readOnly\":false}},'W10=','fUGGyYCSemnNBrk6_4BLwtnOZkza04X1Y9gDPKytnVlEEYuUG81nDhlBeSfLS6YBBQgc5WpH7nGTJGavGWdSRFSU2yRqk~u9UWrFI1UDhizaqWAypmYVv6nRpLKDtSpxn8zgLw_02fSO4!',1655754697,'SelectionInput_42','','RightNow.Widgets.SelectionInput','42','ZlV5Nmo3Y05TYmRUUXRBSzB_WEh_cHhDVDVQeUxWWGhDTlZCRn5ld3hyV2p2aGxLbWpfWXJrX3BoR3MxSnVQdmplZ1h2MWpCbDdGa05JUWJDYlhBWkpxQmJ6VHFjVklLYzF_UTJCX1BBV1RGZFdTNHlhX3c1MTFmb0NQQlRLMGpiMjZmTGZaTzZJRGp5YkNHOTZfMlNPYWRlVEdqS2dLNTly');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":44},\"a\":{\"label_input\":\"<b>Especificar o motivo de n\\u00e3o questionado: <\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.reporter_other_type\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.reporter_other_type\",\"custom\":true,\"constraints\":{\"maxLength\":127},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlV1SzIydHBIUlpTRkdSeEZzYnlLMkZmeVNwTWZneTZlWmlHVTBpOVd5bWxBWU95WTdjNjRiaGNZQUJVRGZSbGg0ZnlEQkxBQjJ4RzR_WFc0OElUeGpHUXdPMW5BS0hmcE50M2M5QllYTlVUWXBRNU1xeHNMckFEZzNROUxLbWFKVUxMZVRNSm1tYTB5MFJnOVFyYlQ5OWE4RXZxajNyOWJ1\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5Fc3BlY2lmaWNhciBvIG1vdGl2byBkZSBuXHUwMGUzbyBxdWVzdGlvbmFkbzogPFwvYj4iLCJuYW1lIjoiSW5jaWRlbnQuQ3VzdG9tRmllbGRzLmMucmVwb3J0ZXJfb3RoZXJfdHlwZSJ9LCJleGVtcHRfZnJvbV9sb2dpbl9yZXF1aXJlbWVudCI6eyJleGlzdGluZ0NvbnRhY3RDaGVjayI6dHJ1ZX19','fU8Wt_DKw6suQfc5qknKnbf~SQKbC9tlcB~37AIuTpv9DfouZgQ5hqFQTKIsQwetDfmtlLF1rnqpcjpxM~NwWcXmauGSWLFCwYZOFNTwZb3CcXLZhRCOOTCCss7diNbqLDE_qa_WcRszk!',1655754697,'TextInput_44','standard/input/TextInput','RightNow.Widgets.TextInput','44','ZlVOcjdpazcwM1ZYQzZzRVFpeTZQd2dnVFJHcEVpX3lydUZ1U0RNckhkbDRuZXdHeFNUNktzdkt2d1dDN0g1SDZwZ3RTRXpqfkVsYW1ZYXVIb0xScGN3ejlld1ZHYWU4bnU5dTFHZHROZ09zTkszeTVrZ1hOVnRPR3VQeUdmbm40N3h2RjliUFJCSlRyUVY4Mzh6Rl9sdzNhVG4ydmNmTlhO');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":46},\"a\":{\"label_input\":\"<b>Nome Completo: <\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.rep_fullname\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.rep_fullname\",\"custom\":true,\"constraints\":{\"maxLength\":150},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVQQm44bF9DNzcwS2gyYllTM29FQkRnXzNPa2dveFRMY0VTNll1Q2tqcHpNcGtpeEswSm5qSXRrb1NMdlNoT1JNdWoxZDVUN0tnQ0wwQ3VLWVFvMlE3QWdDZlJBRDdyQTdIblM0N1ljMjdvX05JaHZnQXFaSVRGfkNOd29tZG11OVBHbVo2WE1CcHhyeU5MbldoVlhsZlI5VnhxUFlpb0Qx\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5Ob21lIENvbXBsZXRvOiA8XC9iPiIsIm5hbWUiOiJJbmNpZGVudC5DdXN0b21GaWVsZHMuYy5yZXBfZnVsbG5hbWUifSwiZXhlbXB0X2Zyb21fbG9naW5fcmVxdWlyZW1lbnQiOnsiZXhpc3RpbmdDb250YWN0Q2hlY2siOnRydWV9fQ==','fUowNpNr~85fLmDZ3gybcGb_sVZR2MOuuk3_P4z2QwHhXPf_HqR8_OPVKQlw6dclwfVlupVjv4vqteDJRtA5Yibnxaq6Wb6Bq08xzEAEtWhwkTgSi~HFav~e_lSUv2NYB5LbEK7d29PFY!',1655754697,'TextInput_46','standard/input/TextInput','RightNow.Widgets.TextInput','46','ZlVSRTVyUDVXMThoTlE0TmNIektoMXBnc0tMQ0F2TWJGT0hFVlJaNDFGMzhSZGdPYk5LbTczWjVlbzNjTU1GZzIzd2trcThQalA0fmVsTFdhU1VubzBGTTJOc1A5b0xSNUNCSUVDTjdQWE1kcW4xUEJoZXQyYk5XbE5zNTRKb2dxVmxOVE1Kc2R1bThHWDV5Zk11TGEyekc5ZnNFWHdwWGJU');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":48},\"a\":{\"label_input\":\"<b>Profiss\\u00e3o:<\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.rep_occupation\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.rep_occupation\",\"custom\":true,\"constraints\":{\"maxLength\":127},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVjc0dCV2VqbUdJRngzdEFoaTN6SFJ3V3hSWGF6bH5uY3NLSmNrdH5PcGNPWFJ0Y25xVGRYM052endodlRoNTJhOWt1SnZ0MEd1M3RkQmFwMlVLfkFUUXJHQU1hVm1rTlVYbDIzOENvc1B0RmZmUGpjaGVPREh0Z3J3ZU9USmQzd1UyeUpyR343NTN5cGNkY2FabTYxN18yb0p5R2RTcTNZ\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5Qcm9maXNzXHUwMGUzbzo8XC9iPiIsIm5hbWUiOiJJbmNpZGVudC5DdXN0b21GaWVsZHMuYy5yZXBfb2NjdXBhdGlvbiJ9LCJleGVtcHRfZnJvbV9sb2dpbl9yZXF1aXJlbWVudCI6eyJleGlzdGluZ0NvbnRhY3RDaGVjayI6dHJ1ZX19','fUMdh1mx7c1FvP0vo9NQsyniK~IWBRq~A7wDDS8dF0BV3LwF3nKQn_tMkYnBtr1oqiSgxUmNa3JJkgL8O34QZ_x9KZ2ajETtHk8l4iLL_0yf3gVD0IHThFXRWJJQQGQRtIMA6PJK_4qAs!',1655754697,'TextInput_48','standard/input/TextInput','RightNow.Widgets.TextInput','48','ZlVWMmxndDJ6RURCYVdneGZVd2l3RW1xNE9lYTRjdVdxYlRFNWdla3k3UG5lenZqUVoxYWdWd2xJb0Y2VFJPaXA0bXViY050V05yQjJZQTlCbkFvWjYxSGFIYTMyN2VaNlB4ZlF2dmxVMEJiNV92MUdETDhtTklUNmNPRGJiNEVZeVY4alVnQ1NxR3pyTG0xUXZ_VlNpTDNEdHNnRUJ4YXlP');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":50},\"a\":{\"label_input\":\"<b>Telefone: <\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.rep_phone_number\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.rep_phone_number\",\"custom\":true,\"constraints\":{\"maxLength\":40},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlUyeFZmWkhWcXlGUjZzdDEwZzV6Vjk5cG1BM1FNN2QyS2M5dWQ3RHJKeURhZ2V0YXhRTHFfflVlTHJNaGhVd1VRVX53N2VMYkdJRGVOTHNhdzJZYm1HOGtPcmJzSXd5Mm5EYjR6NGFsbzR5NlRZVF9veElGWDdjUjgyeWQ1UlZPekFncH44ZEhPSzhTMjlndEp_Sl9oN01IWWJjb35YUlpf\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5UZWxlZm9uZTogPFwvYj4iLCJuYW1lIjoiSW5jaWRlbnQuQ3VzdG9tRmllbGRzLmMucmVwX3Bob25lX251bWJlciJ9LCJleGVtcHRfZnJvbV9sb2dpbl9yZXF1aXJlbWVudCI6eyJleGlzdGluZ0NvbnRhY3RDaGVjayI6dHJ1ZX19','fUwYJSzVU8gwTehJKMSUJH6iFZu291zSl2M8Ut1j1UFbh091B3WdpaK_M6gYpLS1avOMlIaBy5Lz8aQkaYLcQXbCIXjOprBJOqrV8gm5ClHLPjnmL_yRwMjdEdna_r9sEph5c~PJL~zuI!',1655754697,'TextInput_50','standard/input/TextInput','RightNow.Widgets.TextInput','50','ZlViRWxPZzh_NlFkVX5rdkp_R1BndHcwTGhRblhxdXpjUUVocmNMRllsN05HcV9ZbDZJc0JEQkNFZE5ZOUhpWjVGRzg1cnhhbGN_ajZ_cjJ1QnJQX0dNN2l0U0lkTm5hZDNiVFlTN1RjWGVobGcyaldIeX55d2ZzbG5naU1FM2xya2JWcnQ0Umx_Y09EOW56VndIOEd5WDZIS35GWm5xQVhr');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":52},\"a\":{\"label_input\":\"<b>Email: <\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.rep_email\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.rep_email\",\"custom\":true,\"constraints\":{\"maxLength\":80},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlViVU14S0RraE9xd2JJWDFlYWJHMHhnN0hNcG9DYzJJT21lRkJPYjZFWUlUa1JKVVF0S0l0ZWo1dUZCZEN3fk5FZEMwQ35QSHNQTGJXRTBEV09tWH5LWDlLRHV3NlBva1B3U3RERU5YQ0ZtM3RJZFhkSXgwaWNzWXdjeFIyY2FnUjRoNGh2QVlQV09VcjRkaldidE5TV1pBRXBKbUdWNUZC\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5FbWFpbDogPFwvYj4iLCJuYW1lIjoiSW5jaWRlbnQuQ3VzdG9tRmllbGRzLmMucmVwX2VtYWlsIn0sImV4ZW1wdF9mcm9tX2xvZ2luX3JlcXVpcmVtZW50Ijp7ImV4aXN0aW5nQ29udGFjdENoZWNrIjp0cnVlfX0=','fUtbiGUSdJ3yxQiH5Rd56Non6qhd8ytZxlLVlwpYHOKTs1nVfOIWSeM2fVnfWiPcOctQrXOB47LJww8TlPaI~W4Pfk1AkVG2osViA2GqEew5j92EMitmIZ0BMXe7seiqOqnpT5tmW0cj8!',1655754697,'TextInput_52','standard/input/TextInput','RightNow.Widgets.TextInput','52','ZlVSVEJ1Mk5YRHJtfnhMTWdzb05GVXVSOG1SNUU3MmFRY2VSWkdDamlkalEzVWxOdHRKZmV0VEM5NXphcFdEd3N0MHVqZ0g3cTdJMFhCQWJERXEwWEFKdm90RTNQREZTUUZhV21FcE9VcEtxY0U5S18yekluV2VRVmlQYTRBZzliTE1_Z0ZSVlczYVF5WG1hQmRxaUVxTmRIOFFEaTg3RW1M');\r\n"
				+ "W[c]({\"i\":{\"c\":\"SelectionInput\",\"n\":\"SelectionInput\",\"w\":54},\"a\":{\"hidden_items\":\"\",\"label_input\":\"<b>Em caso de queixa t\\u00e9cnica, foi orientado contato com o Fale Pfizer?<\\/b>\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.rep_fale_pfizer\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"initial_focus\":false,\"validate_on_blur\":false,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"display_as_checkbox\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"selection\"},\"j\":{\"type\":\"NamedIDLabel\",\"name\":\"Incident.CustomFields.c.rep_fale_pfizer\",\"custom\":true,\"constraints\":[],\"mask\":null,\"readOnly\":false}},'W10=','fUp7OcHBnA4GRPL_ENMaRNu0tutIkwcoiJOshXwp15Owm1rugn2JW8f6z_WYiSEA2FRx1FdYTEKjlbSwivcWQ44xIy8mxBi766jEgIgOKyNYwJU0gWuSDGsgrid_iCt9BPnNfXezAMJa0!',1655754697,'SelectionInput_54','','RightNow.Widgets.SelectionInput','54','ZlVXTFoyRm9QRTRfcU1PQ01RY2VWNldFOXZxTzRkeEgyU3dpbkwzbExPZ3lTSjlKM0RRR1ZEZVZ1NElUTGlIU0U5NX42cXlYV3IyT1lMOGo1STM4Q2RhWW5tQVRKaUkzUXNJS25ZalVDSnFNVjdjU3hNazBPSm56bmdtbnlCRkNLMXZEeW5KamFUQUFBd0dnc01ObjVSMTdaTms1Q0VTZThl');\r\n"
				+ "W[c]({\"i\":{\"c\":\"SelectionInput\",\"n\":\"SelectionInput\",\"w\":56},\"a\":{\"hidden_items\":\"42,43,44,45\",\"label_input\":\"<b>O m\\u00e9dico prescritor ou de acompanhamento foi informado sobre o caso?<\\/b>\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.physician_oriented\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"initial_focus\":false,\"validate_on_blur\":false,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"display_as_checkbox\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"selection\"},\"j\":{\"type\":\"NamedIDLabel\",\"name\":\"Incident.CustomFields.c.physician_oriented\",\"custom\":true,\"constraints\":[],\"mask\":null,\"readOnly\":false}},'W10=','fUWPeqNYXfnJh9MDPxc_VPyR4r56LorrVoeuA8UKW8L_BYe4BlOzPoMHxtonFTLQJNZXsjRv8NObaP2uD8wt1~Rbl3xa5UOoBfdIpAEEHRqzxNdqiVv9qyiTe530eyceh5g8uHyif2VGE!',1655754697,'SelectionInput_56','','RightNow.Widgets.SelectionInput','56','ZlVWTGpsZTdzQ0l4RDhmRXpfa2x0c0h0N1hRS1J2MmV6QTVrUDNzYnhUS0t0d1dGaG1uNE8xcXBPdlpMVVI0NERXajJHbmo0MDRvUnlsbVdDZHZ4VHdHa1g2ZzV0WWxkZ3oybDZyZDM5SU9pMDNMa09OSUxGaWhyM0ZBY1N_c1BDOG9XVjFIam1jbDFzUXNVRDRUVVVKdXdlMEhGNFRtb243');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":58},\"a\":{\"label_input\":\"<b>Especificar o motivo de n\\u00e3o informado:<\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.Pfizer.PorquePhysicianNaoOrientado\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.Pfizer.PorquePhysicianNaoOrientado\",\"custom\":false,\"constraints\":{\"minLength\":1,\"maxLength\":200},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVyV09McXd2fn5tRnNieV9oaDlCcXoxYlBfMVRhYmFreERxTmwxcnNuOHhGSlprSEhzM0FaNXQ4dEtGdlJ6cDVWQVh4VXFKaWlnbzBzNX42S3g5Y3duS2lMNktDcn5oNm15c2s2NFB6eE5ycX5TTF9oel9aRWNmakJQYk95Mktuc1E3VXkweF9XTDRaaEduUXR1cWdxX3ZINjFTMW50dkhm\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5Fc3BlY2lmaWNhciBvIG1vdGl2byBkZSBuXHUwMGUzbyBpbmZvcm1hZG86PFwvYj4iLCJuYW1lIjoiSW5jaWRlbnQuQ3VzdG9tRmllbGRzLlBmaXplci5Qb3JxdWVQaHlzaWNpYW5OYW9PcmllbnRhZG8ifSwiZXhlbXB0X2Zyb21fbG9naW5fcmVxdWlyZW1lbnQiOnsiZXhpc3RpbmdDb250YWN0Q2hlY2siOnRydWV9fQ==','fUiJcdXKCfvNXiQNKVywDnbBKK4owOt6blZabd_wR5fTaBE6eXSDgFJ_fD3Le0UFqTar8HK1XZ5D1rlzDPsatr5NsFVXG8o0Bx2CZ89YiSACyZSFxZWH3c2PZPiBY7DcG_LG65wvE3Gyw!',1655754697,'TextInput_58','standard/input/TextInput','RightNow.Widgets.TextInput','58','ZlU3T3FzMENyYnJUTFF3SzNlWXkzdHVnRExxYzFvX3piR1VOTzhpV0FhbUswcVVxfkFaMFVjb2QyaG1BWDY0bFpSZXFzWmw4b081RWU5RHJBaG9uUEJqcWlCUWpHflB0MVZHc0dCMEIybmNsbGVwYkh3amRWOFZoRzV6aTZNeGg3bnM3OWdvc1hxbkVWZ1ZPQlJKN0lNa1pUSkFwa0lIY2xj');\r\n"
				+ "W[c]({\"i\":{\"c\":\"SelectionInput\",\"n\":\"SelectionInput\",\"w\":60},\"a\":{\"hidden_items\":\"136,137,138\",\"label_input\":\"<b>Relator autorizou contato com o m\\u00e9dico?<\\/b> \",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.discussed_health_professional\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"initial_focus\":false,\"validate_on_blur\":false,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"display_as_checkbox\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"selection\"},\"j\":{\"type\":\"NamedIDLabel\",\"name\":\"Incident.CustomFields.c.discussed_health_professional\",\"custom\":true,\"constraints\":[],\"mask\":null,\"readOnly\":false}},'W10=','fUdPLYfr4hcTKl6zjPQWVfuhTcrlI94wjmuGWj2tVVvsHGlK60g~TxPpugTRzKoz8LovuypDR2kbEnugFngsrmzz3jDl~bDWhfIaUwwhJ6H9isFIYMghbmek7k0RyIVRcxf4Q68B0v8Ik!',1655754697,'SelectionInput_60','','RightNow.Widgets.SelectionInput','60','ZlVRSHo0WktiY3RkRk4xVFhXM2JoUjk1d05XQUFXMUNkM3ZNbWRHTFdnbDhGQmcyNTFKNGxyQTJWfjJVeGhrRmlxYVY4MHdMaURRckJ6X3cxbVRjTWM3MmJLcjMydERzQWtxZkJ3cXNvNFdodUtEM0pwS3BRdEVYSn5yVG9COVZSeXd0V0lTZFVYMTRfWTFvdlJpVHNwUF9TUHpVNXFNVnZS');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":62},\"a\":{\"label_input\":\"<b>Especificar o motivo n\\u00e3o questionar a autoriza\\u00e7\\u00e3o de contato:<\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.Pfizer.PorqueNaoQuestionarAutorizar\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.Pfizer.PorqueNaoQuestionarAutorizar\",\"custom\":false,\"constraints\":{\"minLength\":1,\"maxLength\":200},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlU2N1lLcDFUb3JYNn5FTzdqRUlSQjJOWWdOQmRKekpZMFRpaU1od0gxaUEwV08xZlZaX0JaQW9tZXM3ZVVhSTF6U0xZUFJvT1Jvc1h4QlFqVmVwTzBjRTlveElDQ1VHSGIzdXZLNFZZOHZCWX5GQlo5eDJhb20zSDVYdncxcVNtWFNvcXo2WmJVRV94ZEZYN3dJeEo0dGJ1ZEFTb3RPbVVx\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5Fc3BlY2lmaWNhciBvIG1vdGl2byBuXHUwMGUzbyBxdWVzdGlvbmFyIGEgYXV0b3JpemFcdTAwZTdcdTAwZTNvIGRlIGNvbnRhdG86PFwvYj4iLCJuYW1lIjoiSW5jaWRlbnQuQ3VzdG9tRmllbGRzLlBmaXplci5Qb3JxdWVOYW9RdWVzdGlvbmFyQXV0b3JpemFyIn0sImV4ZW1wdF9mcm9tX2xvZ2luX3JlcXVpcmVtZW50Ijp7ImV4aXN0aW5nQ29udGFjdENoZWNrIjp0cnVlfX0=','fUORvXc0x5A4LPPPEOGz98CJu67itRKTwoB~~uWkF1iNbbtmPyFb5JCwa82NsdL9q8GD1oaTWTVDoFvu~V5jNXM23mldFw7t92pvHEfHe4fZms5bS~5hnKmSV9WLBvhEaagex8BTMin0U!',1655754697,'TextInput_62','standard/input/TextInput','RightNow.Widgets.TextInput','62','ZlVDMmE1ZX5EWnNxOXlXT1AwSmx3RUNhMlpnNzFYWEx3bU1sOFZUckpadWEwWURoTEJEdHJtR1pvUkZiOVVvaHhwMFJlVTNkMnFaMlBjZF9nc1c4cFV6aHJVWXpYWlFjbmNab3Rqa1BFMzg0b3FPckwyQWhnVllxYkxtMU1jdkFoNXFmNTRnRk9MbVRLVmdMYUdzT2Q1aVIzMnpQTlU5fkVf');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":66},\"a\":{\"label_input\":\"<b>Telefone:<\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.phy_phone_number\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.phy_phone_number\",\"custom\":true,\"constraints\":{\"maxLength\":40},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVfZ0w2Q3JrUDVidWxqdWptVm13MlVHZnhTfjhua05uNmdUeGpDa3JCUEM0UTJuQmxHTUtpNEpoZ0tfQ2U2akEybjlicGNYX1lDeVN0S3FNaDBkTWNrNWhnbEpCanpaMGQ3Q2w0UmRCRmpKb3BDVFZQcE4wMkRLQ1BwUE8yb2xPSVVpSEZLU1kxREVqbnd2a0Y5Z0tHMTh6bUhQdFBmelJz\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5UZWxlZm9uZTo8XC9iPiIsIm5hbWUiOiJJbmNpZGVudC5DdXN0b21GaWVsZHMuYy5waHlfcGhvbmVfbnVtYmVyIn0sImV4ZW1wdF9mcm9tX2xvZ2luX3JlcXVpcmVtZW50Ijp7ImV4aXN0aW5nQ29udGFjdENoZWNrIjp0cnVlfX0=','fUtjKcuf6ziu11_T4upvNtbA~itkvnjHGZ8NhYjH4VgNgeCvIAUvlaNsnDHi~sjFZA7WK_BeiAGYz9xMeVmtavZHVegD9qbf508VHDmoqK9oMNOOdEuqDWdfW8RFZYtKfeH8ANXrKcM~o!',1655754697,'TextInput_66','standard/input/TextInput','RightNow.Widgets.TextInput','66','ZlVET1lLbUZXdEZoMGNmcmZRNGpyTGZDUk5JTUhTZHhhRW0yMnBFOG0xXzJ2RjhMd3ZTdnU5V3NoTENCM1F6cDE2OUw1SnJiYzZvQnRyTnU4U1A3WGhyN25fRjhqYnlYWldUTjR5SW5OMElVUVdNSDJOflRBczZGb2hrYkFfWHJlc3RjRG5PczJBN25WZzVOREloZHpOXzZ1VkdtTjhybENw');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":68},\"a\":{\"label_input\":\"<b>E-mail:<\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.c.phy_email\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.c.phy_email\",\"custom\":true,\"constraints\":{\"maxLength\":80},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVYVWQ2NVJuXzlaaFIxS3FWVlZyWU44OHFoYkRYdE5qaExvNmF5WmtPSm1YSUljaXJzR3dPX3ZzMXhBeXpYS2tNR0hzZlJRdkdPcUpGUUx6WDhCcTdaaTFTVktwUFE2UDdvdzB3QTlYdEg3flZjY3MyfkxXWTR1bzJNMXZQWnowRmZReTlmbUpkMTJpY3N_bFNyWDhUdnR0UjFVZWY5Umdq\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5FLW1haWw6PFwvYj4iLCJuYW1lIjoiSW5jaWRlbnQuQ3VzdG9tRmllbGRzLmMucGh5X2VtYWlsIn0sImV4ZW1wdF9mcm9tX2xvZ2luX3JlcXVpcmVtZW50Ijp7ImV4aXN0aW5nQ29udGFjdENoZWNrIjp0cnVlfX0=','fUpfejKELrkt_MX0gQqZpwDlWggKArWNnPX4bLtVYWllPm~o2Mumd7Dgy_Xcq_i7PVxgXGvMohHThODbi_foJelpGPvBfuVZgYYGJ4ZMBB3NQOEeI~i3lJvtwXyJgljXpQJw0AxdMkzdg!',1655754697,'TextInput_68','standard/input/TextInput','RightNow.Widgets.TextInput','68','ZlVXNG1ZeVVGbX53WThwTVBiS2d_QTNCWklWMERPcDZpWW9pM1RoeUIwVHVmVkFlc1NPTkI4UUdQSDFqRFVac3ByWXVNanhBVGpSZTNfUEhRTndPNWlPZ3VDX0NLcEFLYk1jZ3J3dk04QnVhWlNiSDBwU2pkdDA0aWN1eFptN2d3dTN5MGdkb0g3TjVBMmZxUDZEM3FfMmZkRWNqcnVyWmFI');\r\n"
				+ "W[c]({\"i\":{\"c\":\"TextInput\",\"n\":\"TextInput\",\"w\":70},\"a\":{\"label_input\":\"<b>Profiss\\u00e3o:<\\/b>\",\"label_error\":\"\",\"label_required\":\"%s is required\",\"name\":\"Incident.CustomFields.Pfizer.PhysicianOccupation\",\"required\":false,\"hint\":\"\",\"always_show_hint\":false,\"tooltip_accessibility_message\":\"Press right arrow and then down arrow key to access tooltip\",\"initial_focus\":false,\"validate_on_blur\":false,\"always_show_mask\":true,\"default_value\":\"\",\"allow_external_login_updates\":false,\"hide_hint\":false,\"existing_contact_check_ajax\":\"\\/ci\\/ajax\\/widget\\/standard\\/input\\/TextInput\\/existingContactCheck\",\"require_validation\":false,\"maximum_length\":0,\"minimum_length\":0,\"maximum_value\":null,\"minimum_value\":null,\"label_validation_incorrect\":\"Validation for the field '%s' failed\",\"label_validation\":\"Re-enter a value for the field '%s'\",\"textarea\":false,\"hide_on_load\":false,\"read_only\":false,\"sub_id\":\"text\"},\"j\":{\"type\":\"String\",\"name\":\"Incident.CustomFields.Pfizer.PhysicianOccupation\",\"custom\":false,\"constraints\":{\"minLength\":1,\"maxLength\":60},\"mask\":null,\"readOnly\":false,\"contactToken\":\"ZlVxVFdfM0Fpa19sMzJCN1pGNHlqdWFmaTNEa1d4a21GX2Z0cThJUDhLNjBTa29KRjNrUU9OSVc5ZXBIaEFGQXkyZ2VUMkI5eUE4WmNTUWtZUmI0V355SU1UamZjN343cDlycERBTDVFZWszaU5CNDRXcXUwZWgwdjE5UXdyaFFzZ0RLbkIzSFRIU3psTEU0T1FCOFRfTENRcVZQWU5Nc0JI\"}},'eyJub25EZWZhdWx0QXR0clZhbHVlcyI6eyJzdWJfaWQiOiJ0ZXh0IiwibGFiZWxfaW5wdXQiOiI8Yj5Qcm9maXNzXHUwMGUzbzo8XC9iPiIsIm5hbWUiOiJJbmNpZGVudC5DdXN0b21GaWVsZHMuUGZpemVyLlBoeXNpY2lhbk9jY3VwYXRpb24ifSwiZXhlbXB0X2Zyb21fbG9naW5fcmVxdWlyZW1lbnQiOnsiZXhpc3RpbmdDb250YWN0Q2hlY2siOnRydWV9fQ==','fUh_yhUj6xv6cR0EqLxDObefYS2mSDjDjonloEIgcKJ2CcveVB~7tdbCaduqDl2C943XERC3XhTShzm9iV64iP~V0UF3fYDlYAWxCMEo1czTbwwPBKlNWv4CnVpUu2~TcN_4PFoRLbcHI!',1655754697,'TextInput_70','standard/input/TextInput','RightNow.Widgets.TextInput','70','ZlVWWFZ0S1BJTnl3RThrTW1oZllLbGJ1Y2ZpWmZJQmZObEhfa3ZLM2RtUm85RW5PX0d4Znc0c2U1c0pWZ2FuNXZrNk9qN0xHd35zVU92fm9XMmlRMFJkZU1wYnVqUjlVZjR3RHN1MjN4RllkaERtVGt5b2FOUUVaS3N1YlgxeWoyalp5V01fdUZhdn5_bHZWWTJzTkkxeTRlbH42eHJoQk5s');\r\n"
				+ "W[c]({\"i\":{\"c\":\"FormSubmit\",\"n\":\"FormSubmit\",\"w\":71},\"a\":{\"label_button\":\"Enviar\",\"label_confirm_dialog\":\"\",\"label_submitting_message\":\"Submitting...\",\"on_success_url\":\"\\/app\\/pfizer\\/show\",\"label_on_success_banner\":\"\",\"error_location\":\"rn_ErrorLocation\",\"add_params_to_url\":\"\",\"challenge_location\":\"\",\"challenge_required\":false,\"timeout\":0,\"flash_message\":\"\",\"unsaved_data_dialog\":false},\"j\":{\"f_tok\":\"ZlVKMlBqZ0FoM2JIS3h4RFhod3l6UzNHYzVOc2hpV1d0ZW5mVU05cVNySUt4c21nNkNKN2lRWUI0dFc4Z0NjVmU3eHZLR25lSHFlTTVyOW5DN1dLU1d6ekxqa0dJMEVlZTQ0TkVRUDFPNFVDM2xUREE1Q1E5dkUwbFJvfldrWVFYSmlueXN3VHYyWHNWbmJTNFQ1VlVRamM3aTNsNUw2SU5R\",\"formExpiration\":1500000}},'W10=','fUm3t8tPAWTp87qp5WwtqN54OSPOqAZcSeLdaUTmmA1u500cOeo_fzT9mQGHQS~6OrL1AdqnrYqFrt_Zf4rOhcNns_3BBCCVk7fqtdn2Kpiy2ZqBH3cM9ZJUYhZBIfD8pMR0l0Updz7lM!',1655754697,'FormSubmit_71','standard/input/FormSubmit','RightNow.Widgets.FormSubmit','71','ZlVYQ05GZDdBR01iYTJad2k5b3dmRmdtVTZjejhoZ2t0WkZNMHRXODIwSmZQUUY4YTk2NFp4SGwzbGJCWE1OTFV5VmRNRW56TXplQTZkZDFZbHpjfm1nMXRmbGlyNXJ3R1RGVlNja3hva3M4czhmbHlORmFvMFRmWW1xZmJWdGxuNXlKS1VfWVZ4N3VObTJqVlhsQkZiTnlwQX5RWG1WX0RL');\r\n"
				+ "})});\r\n"
				+ "/* ]]> */\r\n"
				+ "	</script>\r\n"
				+ "	<script type=\"text/javascript\">\r\n"
				+ "		var _rnq=_rnq||[];_rnq.push({\"s\":\"xPAVb4Ip\",\"uh\":\"db71da75\",\"uc\":\"azimute--tst1.custhelp.com\\/app\\/pfizer\\/ask\",\"b\":\"ca235398\",\"i\":\"azimute__tst1:azimute\",\"f\":\"rnw\",\"p\":\"Customer Portal\",\"v\":\"21.11.0.1-b261-sp4\",\"th\":\"www.rnengage.com\"});\r\n"
				+ "(function(e){var b,d,a=document.createElement(\"iframe\"),c=document.getElementsByTagName(\"script\");a.src=\"javascript:false\";a.title=\"Action Capture\";a.role=\"presentation\";(a.frameElement||a).style.cssText=\"position:absolute;width:0;height:0;border:0\";c=c[c.length-1];c.parentNode.insertBefore(a,c);try{b=a.contentWindow.document}catch(f){d=document.domain,a.src=\"javascript:var d=document.open();d.domain='\"+d+\"';void(0);\",b=a.contentWindow.document}b.open()._l=function(){for(var a;e.length;)a=this.createElement(\"script\"),\r\n"
				+ "d&&(this.domain=d),a.src=e.pop(),this.body.appendChild(a)};b.write('<head><title>Action Capture</title></head><body onload=\"document._l();\">');b.close()})([\"https://www.rnengage.com/api/e/ca235398/e.js\",\"//www.rnengage.com/api/1/javascript/acs.js\"]);\r\n"
				+ "	</script>\r\n"
				+ "	<script src='/euf/core/3.8/thirdParty/js/Markdown.Converter.min.js'></script>\r\n"
				+ "	<!--iuvY#YY!3VJpU60s10BTky@Culc1hvcNOyUJdL2b5qxb7zF8SK3%Bq*oMHcDzITdRWeDjcrnAADrZL$w$wn4ZM*kBvJ46JYq7W8%reVS$o2HF$i1f71mpz8q8J5trwn2n!LXrZDIJl1i&Lf@a^xkk(W1l50g9wbtk)dsBv)^5I%&tUT^hmZMQtFmb%3GPO2uJAbPs7(jMTyqoCxyx4H*OD#)fZUO(uIkin!UVNzqB(fXYsOLmzfTC!itPD&v3B7$24%v42ELqkjr%M^hyU7dNNyKx@uLp783iToTgZClhj^t#0lht6fiJ47j(YbTpOw)2^0qHSxLk$SBktq5kHLpIJ36R!*XkjA2C*N3vc0S*lcqwkvo&UoIxfSoP*Kk8TBcX2K%5boiZE!JUqR*%HBHDKeKzfmZ402tCmTqHrR%Q21UksUYRf$XRM936M%4TQ($eFt1dj!g2rl@)1kD4QUckD4kSH2F&yLML^)D8vb0U5x%cNM5cJoWFMFIjV$j@lDAt(aNOFg4Uj4MzAF%isAVOQZxiwtg*#zim)32DCeQX@L1UkhEELDrh$^64d#1490N2xUUPy@qYzRP34d1yFUO2*8dC%4UR@gntBXxt0CMw3jADQrv*86FPOG*L@A@hjdDpnvcK(uIRU&$4kDS5OAlom!mZ#$Bv29APZamY0i!b^df%MbSd0BQmOS5lg*#foEY3a)bBpD7iM47ch^R*CI9W2iC5YVerQJR9GQXtZz4ZuzWdN-->\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
	}

}
